### ISSUE TITLE
Lucky egg used

### ISSUE THREAD

**Issue by amaslkw** [Ar1i/PokemonGo-Bot#2565] opened 2016-08-10 13:23 UTC
when i run the bot, i suddenly saw lucky egg used.

i quickly stopped the program and tried to see if i check any box wrong

i did not check any "use lucky egg when xxx" options 

and the bot has not been using my lucky egg all along until now.

please help. i hav 3 left. and i dunno if the bot will use it again after half an hour

**Comment by NaveTK** [comment] 2016-08-10 13:24
why not let it use him? he's way more efficient when using the lucky egg than a human can possibly be

**Comment by xRealMaks** [comment] 2016-08-10 13:28
are you sure you uncheck both?
![pic](http://i.m4ks.cf/RXZ3LGfC.png)

**Comment by amaslkw** [comment] 2016-08-10 13:29
yup unchecked both already.
i was shocked coz it nvr use the eggs in previous versions.

**Comment by amaslkw** [comment] 2016-08-10 13:35
i will update half an hour later. see if it will use another egg

**Comment by arjunvegda** [comment] 2016-08-10 13:36
damn... I lost eggs

**Comment by Efotia** [comment] 2016-08-10 13:38
Same here but dont worry about eggs once you hit +35 you'll get tons of coin from gyms

**Comment by b3shoy** [comment] 2016-08-10 13:56
The problem is that the bot is auto selecting Use lucky eggs if not running on each restart, and removing the Auto Incubate selection also.

CC: @Ar1i @Logxn

**Comment by arjunvegda** [comment] 2016-08-10 14:07
@Efotia how ?

**Comment by amaslkw** [comment] 2016-08-10 14:12
its not using any more eggs now after half an hour.

**Comment by gummyruler** [comment] 2016-08-10 14:25
It used a`ll my eggs even without those checked

**Comment by Efotia** [comment] 2016-08-10 14:52
@arjunvegda Once you have enough strong pokemons you can takeover gyms and can get 10 coin from per gym if im not wrong you can get 100 coin/day

**Comment by arjunvegda** [comment] 2016-08-10 15:06
@Efotia Ohh yeah I am still doing that. But it gives me just 10 coins :/ So If I takeover gyms and place my pokemons at 10 different gyms and then can I redeem 100 coins together ?

**Comment by FvG90** [comment] 2016-08-10 15:15
yep thats how it works :D

**Comment by wicker558** [comment] 2016-08-10 15:23
Same happened to me, I have everything unchecked except for the GUI, I think it is a bug and should be fixed.

**Closed** 2016-08-12 17:38 UTC
Labels: major bug
