### ISSUE TITLE
LURED pokemons still NOT DETECTABLE

### ISSUE THREAD

**Issue by Eichelziger** [Ar1i/PokemonGo-Bot#2382] opened 2016-08-09 17:15 UTC
Im kind of getting the feeling that the most important missing content here is getting pretty damn forgotten.
We need the bot to be able to catch the lured pokemons. And we need it fast AF! This would easily double if not triple our XP rate per hour. PLEASE go for it.

cheers

**Comment by PippoAe** [comment] 2016-08-09 17:19
this (and egghatching of course)

**Comment by xRealMaks** [comment] 2016-08-09 17:26
Any proof the bot dont catch them?
Cause there is no difference between normal and lured Pokemons.

**Comment by Eichelziger** [comment] 2016-08-09 17:34
everytime i log in via nox (and i always make sure im logging in at the same coords where the bot was at), there's tons of lured pokemons literally surrounding me, im pretty sure others have noticed this aswell. there's 58 pokestops where im at (central park, 400m walking radius) and every time the bot reaches a pokestop he's not catching anything at all. im pretty certain that the bot is not detecting the lured ones properly.

**Comment by Logxn** [comment] 2016-08-09 17:40
it detectes every pokemon.
Because there is no such property like "luredpokemon".

**Comment by PippoAe** [comment] 2016-08-09 17:56
I'm pretty certain there is (or atleast was) since older pokemon scanners showed a "Lured Pokemon: XXXX" attribute on them.

**Comment by beasttry** [comment] 2016-08-09 17:56
egg hatching is needed!

**Comment by xRealMaks** [comment] 2016-08-09 17:59
@beasttry. Get your phone, disable GPS, start pokemonGO, put your eggs in incubators, ..., PROFIT :dollar:
The devs develop the bot in their freetime, so please be patient. It's on their To-Do list

**Comment by Ritzii** [comment] 2016-08-09 18:15
You don't even have to disable GPS, the game won't softban you if you don't use anything around the area you are in with your phone. Just load it up, switch eggs, close it again and boom, ez

**Comment by PippoAe** [comment] 2016-08-09 18:17
1. Opened Nox, lured pokestops near me.
https://postimg.org/image/hzgr8yp6d/
2. Closed Nox, set exactly the same coordinates and started bot with 1km/h and 20 meters radius.
https://postimg.org/image/akcjak6x1/
3. Some of the pokemons were catched immediately.
4. Closed bot and immediately started Nox again, about 4 pokemons popped up.
https://postimg.org/image/p6hfffwxx/ 
5. Closed bot and started nox again.
https://postimg.org/image/i523xfr1h/
Bot doesn't see the pokemons and starts a restart-cylce because the stops have already been flicked.

**Comment by PippoAe** [comment] 2016-08-09 18:20
Since 20:08 the bot cycles at the position and hasn't catched any pokemon.
Loggin in in nox shows about 5 pokemon.

**Comment by PippoAe** [comment] 2016-08-09 19:44
@xRealMaks or any other dev, have you been able to reproduce the behaviour?

**Comment by xJustx** [comment] 2016-08-09 19:52
Currently it's not working.
But it will be added soon :p 
Please be patient.

**Comment by czokalapik** [comment] 2016-08-09 19:52
I can confirm that, i set walking speed on bot, checked the path for 1min, closed bot, opened nox and ran the same path, there was 9 pokestops with lures and all of them spawned pokemons. bot doesn't detect lured mons.

**Comment by PippoAe** [comment] 2016-08-09 20:02
@xJustx I'd suggest you to let this issue in the open state.
It has the steps to reproduce and more people might even post some useful information.

**Comment by PippoAe** [comment] 2016-08-09 20:26
Ty

**Comment by jmo93** [comment] 2016-08-10 00:38
Yes , i find out that the app poke live also can't show pokemon from lure.
The bot don't catch the lured pokemon

**Comment by czokalapik** [comment] 2016-08-10 06:06
I have checked PokeFarmer, it appears its recognizing lured mons, there is pokemon at every pokestop.

BTW, PokeFarmer's feature of displaying pokestops, gyms and pokemons locations on map is great, i'd love to see it in this bot.

**Comment by PippoAe** [comment] 2016-08-10 07:20
Why is this labeled "help wanted"?
This clearly is a defect.

**Comment by PippoAe** [comment] 2016-08-10 08:19
xRealMaks warum? waaaaarum? 
Die Behebung dieses Problems würde die pokemon/h bedeutend verbessern, eine oder eigentlich DIE Kernfunktion des bots.

**Comment by xRealMaks** [comment] 2016-08-10 10:03
@PippoAe wir wissen nicht, wie wir es fixen könnten.  Wir können nichts fixen, dessen Ursache nicht bekannt ist. Selbst wenn, die API provided kein "luredpokemon" ö.ä. properties von pokemons, somit bleibt das issue ein "help wanted" bis jemand ordentlichen input (screenshots) gibt und geklärt ist ob es sich um ein Bug handelt. Selbst wenn es so sein sollte: Wenn die API es nicht liefert, sind uns die Hände gebunden.

**Comment by PippoAe** [comment] 2016-08-10 15:02
Okay I think I found one part of the problem.

You can only pull the MapObjects one every 10 seconds or you'll get an empty message.. (https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/94)

If the bot is started he does one mapObject call for the PokeStops, if he finds one, he does one mapObject call for the Pokemons in ExecuteCatchAllNearbyPokemons()

**Comment by Eloick** [comment] 2016-08-10 17:53
So if we walk at minimum speed it will let more time to detect pokemon maybe?

**Comment by PippoAe** [comment] 2016-08-10 18:35
Yes, it kinda looks like this.
Since the API seems to only allow to detect new pokemons every 10 seconds.

**Closed** 2016-08-12 17:38 UTC
Labels: help wanted
