### ISSUE TITLE
IV Higher transfering not lower

### ISSUE THREAD

**Issue by blaik2k4** [Ar1i/PokemonGo-Bot#2678] opened 2016-08-10 18:20 UTC
Im Sure im keeping low IV Pokemon and its transferring higher

**Comment by pokerave** [comment] 2016-08-10 18:20
show settings

**Comment by kazzaluis** [comment] 2016-08-10 18:22
![image](https://cloud.githubusercontent.com/assets/1984839/17565522/63e7bbd2-5efd-11e6-8814-d14067d0c26f.png)

**Comment by eLDeMe** [comment] 2016-08-10 18:24
I was waiting for someone opening this thread hahaha, yeah, same for me and i have configured correctly, I keep older versions and I can confirm is a bug of this new version

**Comment by dreamboatcap** [comment] 2016-08-10 18:29
https://github.com/Ar1i/PokemonGo-Bot/issues/2662

**Comment by FerMedina86** [comment] 2016-08-10 18:47
![image](https://cloud.githubusercontent.com/assets/20867022/17566341/9d3dc96e-5f00-11e6-91d0-7c1590206d50.png)

it's not working, i had to close the bot

**Comment by dreamboatcap** [comment] 2016-08-10 18:51
https://github.com/Ar1i/PokemonGo-Bot/issues/2661 just uncheck the transferfirstlowIV

**Comment by eLDeMe** [comment] 2016-08-10 18:53
I've uncheck the option and now transfer the lower one, seems like its inverted

**Comment by FerMedina86** [comment] 2016-08-10 18:59
i know , i did that, thanksss.. but i lost my higher pokemos =(

**Comment by army69** [comment] 2016-08-10 19:14
![erorr bot trasfer iv pokemon](https://cloud.githubusercontent.com/assets/20955864/17567378/a4d31046-5f71-11e6-8639-ef998a2a9c04.png)

same :)

**Comment by FerMedina86** [comment] 2016-08-10 19:15
eLDeMe commented 20 minutes ago • edited
I've uncheck the option and now it transfers the lower one, seems like its inverted

**Comment by emilie253** [comment] 2016-08-10 19:22
@kazzaluis  where do you farm growhilte to have a lot of him? ty

**Comment by FerMedina86** [comment] 2016-08-10 19:24
Santa Monica  =) al ot of  growhilte

**Comment by Ar1i** [comment] 2016-08-10 19:28
@army69 should be fixed in update

**Comment by FerMedina86** [comment] 2016-08-10 19:29
thanksss a lot !!!

**Comment by emilie253** [comment] 2016-08-10 19:31
@FerMedina86  ty
@Ar1i ty too ^^

**Comment by eLDeMe** [comment] 2016-08-10 19:36
@Ar1i no, its not, I've still have the problem

**Comment by Ar1i** [comment] 2016-08-10 19:37
@eLDeMe whats the exactly problem then?..

**Comment by eLDeMe** [comment] 2016-08-10 19:42
@Ar1i 

![image](https://cloud.githubusercontent.com/assets/20787975/17568244/32fd5c0e-5f00-11e6-8d38-f79a14f7c034.png)

**Comment by eLDeMe** [comment] 2016-08-10 19:47
@Ar1i  since when it sets the IV percent in decimals the bot is transferring the highest one

**Comment by Eloick** [comment] 2016-08-10 19:47
just uncheck the box and it 's working fine  (inverse of what is written)

**Comment by eLDeMe** [comment] 2016-08-10 19:53
@Eloick Yes, I know, I'm using it like that, but that's not the point, its still an error

**Comment by johnmarty3** [comment] 2016-08-10 23:07
Agreed, still broken in the most recent version. It's throwing away all of my strongest duplicates, the ones with the highest IVs. Unchecking the setting for now, but the damage is done.

**Closed** 2016-08-12 17:38 UTC
