### ISSUE TITLE
Saving settings fail

### ISSUE THREAD

**Issue by InZaNeSkIl1zZ** [Ar1i/PokemonGo-Bot#3973] opened 2016-09-19 17:46 UTC
When I save an account since the latest update and I restart the bot, it doesn't load the settings I made before propperly. So I have to set up the settings all over again. Do anyone know how to fix it? It just says it would be the config file wich is broken.
Thanks

![unbenamnnt](https://cloud.githubusercontent.com/assets/21690506/18642873/b659e650-7ea2-11e6-87eb-377cc0f61c7a.PNG)

**Comment by kickz** [comment] 2016-09-19 17:49
same problem...

**Comment by shadowfak3r** [comment] 2016-09-19 17:50
same here

**Comment by Buddhasama** [comment] 2016-09-19 17:51
same problem

**Comment by BOYSA** [comment] 2016-09-19 17:56
delete the config file
but in any case have to be patient because at the moment its not working!

**Comment by InZaNeSkIl1zZ** [comment] 2016-09-19 18:26
@BOYSA Does not work for me. Guess we will have to wait

**Comment by erickrisnarinjaya** [comment] 2016-09-19 18:39
I thought I was alone. Pls fix that, devs. Thanks.

**Comment by mien91** [comment] 2016-09-19 18:48
same here! :/

**Comment by jmo93** [comment] 2016-09-19 19:34
same here

**Comment by MTK4355** [comment] 2016-09-19 20:18
Yeah, yeah I broke it. Please let me know if the latest build saves your configs. Should be available in the Profile select dropdown even if it does not default or claims to be broken.

**Comment by jonilala796** [comment] 2016-09-19 21:03
The issue is still there.

**Comment by MordorGames** [comment] 2016-09-19 21:17
This is the last version, that runs ok https://github.com/Ar1i/PokemonGo-Bot/blob/4022cf668dda9b77cfb2da3be1356b21fad09986/Builds-Only/PokemonGo.RocketAPI.Console.exe

**Comment by InZaNeSkIl1zZ** [comment] 2016-09-20 03:45
Its better now but there are new issues.
- it shows a window wich says that the throw chance is greater than 100% even if its lower (somehow    the window opens twice)
- the password wich is loaded is way to long (also wrong)
- the device wich was choosen before changed back to the 'galaxy6'
- it sets limits for Pokemon, Pokestops and XP

![unbentdfannt](https://cloud.githubusercontent.com/assets/21690506/18656871/4e05f8f2-7ef5-11e6-8f22-cda198f722e4.PNG)

![unbugenannt](https://cloud.githubusercontent.com/assets/21690506/18656884/70f9c640-7ef5-11e6-8437-ea0c73ea474c.PNG)

![unbenavglnnt](https://cloud.githubusercontent.com/assets/21690506/18656889/7520d524-7ef5-11e6-86e5-cf080e7b40ef.PNG)

**Comment by MTK4355** [comment] 2016-09-23 02:00
All fixed now!

**Closed by MTK4355** 2016-09-23 02:00 UTC
