### ISSUE TITLE
Better performance for developing eggs

### ISSUE THREAD

**Issue by PokemonAddict** [Ar1i/PokemonGo-Bot#2948] opened 2016-08-11 16:30 UTC
Tried with different speeds, but doesn't work. Anybody know, how to fix that prob? Only some meters were walked (I guess shirt before the pokestop...)

**Comment by edale2** [comment] 2016-08-11 16:44
I set the bot for 20 km/h and it hatches eggs fine.

**Comment by PokemonAddict** [comment] 2016-08-11 16:57
Now it worked - seems like a server prob of Niantic

**Comment by DHBios** [comment] 2016-08-11 18:01
Just to remind ou to close the Issue, whenever the issue is solved :)

**Comment by justchil** [comment] 2016-08-11 19:05
I'm using 75 km/h and it's working just fine.  It takes a bit because it's only counting the slowdown periods I would imagine.  /notanissue

**Comment by Captnred** [comment] 2016-08-12 03:37
Glad to see everything working

Please close this thread as the problem has been solved.

**Closed** 2016-08-12 17:38 UTC
