### ISSUE TITLE
READ BEFORE POSTING ANYTHING ABOUT ERROR

### ISSUE THREAD

**Issue by Ar1i** [Ar1i/PokemonGo-Bot#2110] opened 2016-08-08 18:48 UTC
Pokemon Servers are laggy af or down atm. Catching the error later. Its not a issue of the Bot. JUST WAIT.

**Comment by DiTechRacer** [comment] 2016-08-08 18:49
Danke!

**Comment by Waiiim** [comment] 2016-08-08 18:50
Danke. Even if I don't think it will stop much people from spamming

**Comment by freetogameplay** [comment] 2016-08-08 18:50
emmm.... i knew it :3

**Comment by Abbasoo** [comment] 2016-08-08 18:51
@Ar1i The bot is working for me.

**Comment by arjunvegda** [comment] 2016-08-08 18:52
I figured out one thing... PTC works fine.. Its google which is having trouble.

**Comment by MadD0g25** [comment] 2016-08-08 18:52
Danke !

**Comment by jeremie152** [comment] 2016-08-08 18:53
ok ty ar1i

**Comment by kazzaluis** [comment] 2016-08-08 18:53
ty

**Comment by instinctftw** [comment] 2016-08-08 18:53
Danke! I think that means thank you.

**Comment by eskirex** [comment] 2016-08-08 18:54
why wrong dir ? = C:\users\Ari\ what is this why?

**Comment by czokalapik** [comment] 2016-08-08 18:55
remove pokemon list csv file from Config folder, did the trick for me

**Comment by jeremie152** [comment] 2016-08-08 18:55
read all its UNSTABLE server not the bot he work

**Comment by Abbasoo** [comment] 2016-08-08 18:55
@Ar1i 
![untitled](https://cloud.githubusercontent.com/assets/20796710/17492044/d2d7dadc-5db2-11e6-827d-e72697eb9b7c.jpg)

**Comment by LetMeKnowYourName** [comment] 2016-08-08 18:55
Thank you for everything, @Ar1i 

You're the man!

**Comment by xuban** [comment] 2016-08-08 18:55
Curiously, the "Latest Build - 08.08 08.14" works for me, the last update no.

**Comment by Raiderman1105** [comment] 2016-08-08 18:57
http://prntscr.com/c37c66 Most time 2/3 windows has this error but its just a lag of Pokemon Go

**Comment by eLDeMe** [comment] 2016-08-08 18:57
@xuban its not problem of the new update, servers are getting down, coz bots hahaha

**Comment by Ar1i** [comment] 2016-08-08 18:57
@xuban cause server is up again, working for me again.

**Comment by malekisma** [comment] 2016-08-08 18:57
Guys. The bot can not work when the server from Pokemon are not Working. 
Thank you @Ar1i  for all you did a great job really i got my Respect ♥

**Comment by Hasagi31** [comment] 2016-08-08 18:57
SOLVED! Uninstall the bot you have extract! Extract again (updated bot) on your desktop and FIRST what you need to do is run it as administrator! and enjoy ^^.

**Comment by xuban** [comment] 2016-08-08 18:57
I'm not say the problem is update, only is a curiously situation hehe.

**Comment by icewick** [comment] 2016-08-08 18:58
THX a lot ... Problems gone newest version Works fine! ...

**Comment by DiTechRacer** [comment] 2016-08-08 18:58
Beste das Ar1i Deutscher is :) Top Arbeit!!

**Comment by jeremie152** [comment] 2016-08-08 18:59
yeah work again you is the best continu good job

**Comment by JCortexs** [comment] 2016-08-08 18:59
[P - 20:55:22] [Farm Pokestops - ERROR]: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchPokemon>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Niantic.Behaviours.CatchPokemons.<CatchLurePokemon>d__14.MoveNext()


    Dont know what to do!! ;(

**Comment by DiTechRacer** [comment] 2016-08-08 19:00
It works Now!

**Comment by jeremie152** [comment] 2016-08-08 19:02
http://cmmcd.com/PokemonGo/

**Comment by jeremie152** [comment] 2016-08-08 19:03
http://cmmcd.com/PokemonTrainerClub/

**Comment by instinctftw** [comment] 2016-08-08 19:03
Everyone I watched my client for about 15 minutes. it will work and then it will spit out a bunch of code that looks like it is broken. But it isn't because i didn't close the client and I waited more and it worked again.... It really just doesnt work because of the server and NOT because of the bot.

**Comment by jeremie152** [comment] 2016-08-08 19:04
yeah i have give some link for see its unstable google and ptc now

**Comment by rickepk** [comment] 2016-08-08 19:14
error if run 2 api?

**Comment by Yogissimo** [comment] 2016-08-08 19:49
Servers are not stable. [http://www.mmoserverstatus.com/pokemon_go](url)

**Comment by TCBlackness** [comment] 2016-08-09 06:18
Hello Ar1i pokemngo new update https://twitter.com/PokemonGoApp
http://pokemongolive.com/en/post/update-080816/ 
They said the recent update that will test the Stage

**Comment by JCortexs** [comment] 2016-08-09 09:16
[P - 11:14:12] [Farm Pokestops - ERROR]: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at PokeBuddy.Niantic.Behaviours.FarmPokeStops.<Execute>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokeBuddy.Core.Routine.<>c.<<Start>b__16_3>d.MoveNext()

 Whats this error?¿

**Comment by drsweg** [comment] 2016-08-09 18:22
Hey guys just yesterday i got an error, it was a bad authentication? and error loading pokemon list. I updated to the newest version and still get the error, any help would be much appreciated

**Comment by kopralnjono** [comment] 2016-08-10 03:09
i just wanna say thanks for Ar1i. your bot is so amazing. even theres a few weakness but overall your bot helps me to raise my level. 
thanks..good job

**Comment by Mordok85** [comment] 2016-08-10 05:08
Danke Ar1i für den Bot. Ich habe schon Videos für Youtube gemacht. User melden mir, dass der Bot den Filter fürs Nichtfangen von Ratata, Golbat und Pidgey ignoriert und sie nicht abschickt. Hast du es auch? Danke

**Comment by thisisnotbyan** [comment] 2016-08-10 11:36
thans Ar1i your bot so amazing :)
good job
can you create free stardust ?
thanks :)

**Comment by catchingpok** [comment] 2016-08-10 15:09
I'm having issues with constantly getting soft banned and the 'unban' button not resolving the issue.  Is anyone else experiencing this?  Other bots appear to be working but I love this bot and don't want to switch over.
[10:09:11] Encountered Zubat CP 106  IV 45% Probability 57%
[10:09:12] Zubat CP 106 IV 45% got away while using ItemPokeBall..
[10:09:14] Encountered NidoranFemale CP 311  IV 28% Probability 39%
[10:09:15] NidoranFemale CP 311 IV 28% got away while using ItemPokeBall..
[10:09:16] We are within 40 meters of the target. Slowing down to ~10 km/h to not pass the target.
[10:09:16] Found 2 catchable Pokemon(s).
[10:09:18] Encountered Zubat CP 106  IV 45% Probability 57%
[10:09:19] Zubat CP 106 IV 45% got away while using ItemPokeBall..

**Comment by MuchachoAlegre** [comment] 2016-08-10 16:19
with new update of pokemon go, should we open no more than 1 instace? I tried to use different proxies for each instace, but it didnt work, now i can only use 1 instace.. Danke Arli

**Comment by jinky999** [comment] 2016-08-10 17:25
I was banned IP, how to unban?

**Comment by 3v01ut10n** [comment] 2016-08-11 10:46
When the Russian language strange symbols, incorrect encoding

**Comment by Hex7i** [comment] 2016-08-12 12:03
Sir! report some pokemon. isn't Transfer!!! exam: Pidgey, Pidgeotto, Rattata or anymore

**Comment by paczkensei** [comment] 2016-08-12 13:06
my unban doesn't work ;/ every time when i unban, i get new softban and i cant do anything with that

**Closed** 2016-08-12 17:38 UTC
Labels: READ BEFORE CREATE A NEW ISSUE
