### ISSUE TITLE
Permanent ban is real, Bot and spoofers*

### ISSUE THREAD

**Issue by james741** [Ar1i/PokemonGo-Bot#3069] opened 2016-08-12 06:40 UTC
Update: Not sure if this a new way of getting solf-ban or not. Going to wait out. Update u guys asap if i find anything new. 

Once you login to your pokemon go account using phone. They going to ask to retry over and over again (failed to get data from the server) This only happen to my bot  account
How i bot: 
google account
daily botting about 8~16h 
Speed 20~50km/h 
39~50k xp / h 
Lvl 30 <-- GG
***share this fast, tell your friends to stop boting and spoofing for now ***

**Comment by Elvete** [comment] 2016-08-12 06:42
? explain ur situation? do u see any message?

**Comment by Polarbear008** [comment] 2016-08-12 06:45
No message , but while loading " failed to get game data from the server"

**Comment by Elvete** [comment] 2016-08-12 06:46
thats maybe rom their servers..

**Comment by cyberwolf888** [comment] 2016-08-12 06:47
I face the same issues with my bot account, i think this is perma ban.
I try to login with another account and its fine

**Comment by sunit1998** [comment] 2016-08-12 06:48
same with me past 4 hours

**Comment by Yotumn** [comment] 2016-08-12 06:48
I can confirm this is permaban, Trying to log on with my phone:
Google Account 1: works fine
Google Account 2 (bot): failed to get data from the server  <-- BUSTED

**Comment by james741** [comment] 2016-08-12 06:50
share this fast, tell your friend to stop boting and spoofing for now

**Comment by cyberwolf888** [comment] 2016-08-12 06:51
Damm thats mean my main account got perma ban.

**Comment by Elvete** [comment] 2016-08-12 06:52
i dont know about u but i can connect in nox and on my phone with my botted account but i cnat king catch the pokemens..the pokestops are ok tho

**Comment by cyberwolf888** [comment] 2016-08-12 06:56
My another botted account (PTC) still work fine but only my main account (google account) got this issues.
I think better stop the bot for now untill the situation is clear.

**Comment by fikrirmd** [comment] 2016-08-12 06:57
it happens to me when i logged in on my phone, but when i wait a hour and logged in with NOX on my PC, everything's fine. is it possible they banned by MAC address not by IP??

my nightmare is started to come.

**Comment by james741** [comment] 2016-08-12 06:58
@fikrirmd
using nox to login samething happen 
game over bro ~

**Comment by IDonated** [comment] 2016-08-12 06:58
I'm botting in my google accont, everuthing just fine, don't know what you talking about guys

**Comment by james741** [comment] 2016-08-12 06:58
@IDonated keep using it then

**Comment by untesty** [comment] 2016-08-12 06:58
For me everything works fine. Maybe they banned you because you guys didn't leave enough time between when you shut down the bot and when you open it on your phone/nox

**Comment by IDonated** [comment] 2016-08-12 06:59
My bot is just working fine: even when it is on disney land tokyo at 150 km per hour lol

Proofs: 

![image](https://cloud.githubusercontent.com/assets/20728445/17614984/1743a470-606b-11e6-9c91-c167ddb78bc6.png)

**Comment by PokePro21** [comment] 2016-08-12 07:01
@IDonated open your account in device

**Comment by Elvete** [comment] 2016-08-12 07:01
guys i think they did something with the sot ban.. they changed it.. now i u get sotbaned u wont be penalized with poketops 2 counter the 40 times spining method..but they kept the pokemon ban...i jsut cant catch them..

**Comment by blasanru** [comment] 2016-08-12 07:03
I can log in with another account without bot but with my other account i cant log in.

Maybe perman ban

**Comment by IDonated** [comment] 2016-08-12 07:03
@PokePro21 what would happen if I open it on my device? Even if I want to I can't, I'm not in tokyo in real life, they would notice I have travelled 50.000 km in 10 minutes.

**Comment by PokePro21** [comment] 2016-08-12 07:05
@IDonated try after some time it will not get logged in device using you bot account try to login in your device

**Comment by fikrirmd** [comment] 2016-08-12 07:05
@james741 maybe they just changed how Softbanned works #staypositiveLOL
@IDonated maybe you can use Fake GPS on mobile and tell us what happen then, maybe you're lucky enough not on banned wave.

**Comment by shuksieno123** [comment] 2016-08-12 07:05
i think thats why
![fehler](https://cloud.githubusercontent.com/assets/20728840/17615090/f23b88c2-606b-11e6-88c1-8cb71183d5e4.png)

**Comment by joy0824** [comment] 2016-08-12 07:06
RIP my Dragonite

**Comment by Elvete** [comment] 2016-08-12 07:06
i am sure that are some regional problems...

**Comment by D003** [comment] 2016-08-12 07:07
@IDonated keep using it, and tell what happen in few hours later lol

i also cant log in my gmail account, and in bot always error with the pokemon list, but in another gmail acc, work fine, so i close the bot

**Comment by fikrirmd** [comment] 2016-08-12 07:07
@shuksieno123 what's that?

**Comment by emilie253** [comment] 2016-08-12 07:07
i use bot (low bot==> 15 km/h and just 1 bot) and i can connect me on my phone :)

**Comment by joy0824** [comment] 2016-08-12 07:08
please keep using it =) don't heed the warning =) =)

**Comment by black9140** [comment] 2016-08-12 07:08
@emilie253 i use the bot like u but i got banned

**Comment by emilie253** [comment] 2016-08-12 07:08
weird

**Comment by IDonated** [comment] 2016-08-12 07:08
@fikrirmd I just logged into my account, I could catch a rattata and one zubat before leaving, no problems here. Could it may be the servers?

![image](https://cloud.githubusercontent.com/assets/20728445/17615139/63515546-606c-11e6-88cb-961c66d60251.png)

**Comment by joy0824** [comment] 2016-08-12 07:09
don't bother warning..just close this topic..they will know when they storm hit them lol. too many are skeptical about this.

**Comment by Elvete** [comment] 2016-08-12 07:09
guys all say that u are banned pls tell me ur region her ein eu i am not banned and i keep my  bot on for 6 days i just cant catch pokemons....i can log in on nox and on iphone i think are the server

**Comment by joy0824** [comment] 2016-08-12 07:10
please continue the usage if no problem occur, we feel lonely =)

**Comment by PokePro21** [comment] 2016-08-12 07:11
http://ispokemongodownornot.com/
servers down think so

**Comment by gummyruler** [comment] 2016-08-12 07:12
Everything is back up|

![back up](https://cloud.githubusercontent.com/assets/20757587/17615198/c8078098-6029-11e6-934c-be3b9c885c7c.png)

**Comment by joy0824** [comment] 2016-08-12 07:14
lets see , loading now with my slow pc. RIP Dragonite..i'll pray for you daily..

**Comment by gummyruler** [comment] 2016-08-12 07:15
@joy0824 RIP 100% Dragonite.

**Comment by Polarbear008** [comment] 2016-08-12 07:15
still the same

**Comment by gummyruler** [comment] 2016-08-12 07:15
Has anyone tried this? 

https://www.youtube.com/watch?v=f-OzQQrtRQs

**Comment by untesty** [comment] 2016-08-12 07:16
don't know what you guys did but I can login on phone/nox with all my accounts.

**Comment by joy0824** [comment] 2016-08-12 07:16
@gummyruler why u said ok then =.=

**Comment by gummyruler** [comment] 2016-08-12 07:16
@untesty  They set their speeds on the speed of light.

**Comment by joy0824** [comment] 2016-08-12 07:17
no, it was default setting speed..i think they are taking some action

**Comment by black9140** [comment] 2016-08-12 07:17
@gummyruler i had the Speed 15km/h and i got this too..so Speed doenst matter

**Comment by PokePro21** [comment] 2016-08-12 07:17
Even i get logged in with my device

**Comment by gummyruler** [comment] 2016-08-12 07:18
RIP in peace then? As what I said. "WE'RE ALL GOING TO GET BANNED SOON." The number of pokestops visited alone gives us all away.

**Comment by Elvete** [comment] 2016-08-12 07:18
idk ... i just took a gym in santa monica....with nox but still cant catch pokemon..i think is a new type o sotban so dont worry..and the login servers are down everywhere except europe

**Comment by mosty1982** [comment] 2016-08-12 07:18
@joy0824  ahaha i had 5 dragonites 100% my level was 37 now nothing :D

**Comment by joy0824** [comment] 2016-08-12 07:18
ok i tell you guys.
it says "we are receiving massive response from YOU" something like that and give them time to resolve the issue.

in translation is : "we know u are fucking botting, please refrain from doing so, we will only temporary ban you for now!"

**Comment by joy0824** [comment] 2016-08-12 07:19
u're god, 100%

**Comment by gummyruler** [comment] 2016-08-12 07:19
@joy0824 I hope that's what it means. Rest in pieces people.

**Comment by Elvete** [comment] 2016-08-12 07:20
ohh nooo i got perma abnned the message poped up...its legit guys go start play legit

**Comment by Thikez** [comment] 2016-08-12 07:20
This Banning is True. I'm from PH

**Comment by gummyruler** [comment] 2016-08-12 07:20
@Elvete Screen shot please?

**Comment by PokePro21** [comment] 2016-08-12 07:21
@gummyruler where are you from ?

**Comment by Elvete** [comment] 2016-08-12 07:21
i cant the twisster in my town cut my hands

**Comment by joy0824** [comment] 2016-08-12 07:21
in pieces...seriously =.= i gonna try again with slower than the default speed 50kmh is kinda fast..lets go 10 =)

but i suspect is the response of bot catching pokemon too fast and stuff..

well gummy i intentionally did not provide screenshot =) i want more "friends" to join our side

**Comment by gummyruler** [comment] 2016-08-12 07:21
@PokePro21 USA

**Comment by joy0824** [comment] 2016-08-12 07:22
ok i going bot with another account with slower moving speed
come on pokemon!! i fear no ban!

**Comment by joy0824** [comment] 2016-08-12 07:22
50 kmh might be too high..lets go 25 or lower, dragonite rip

**Comment by Thikez** [comment] 2016-08-12 07:23
5 kph, like a pro jog-ger.

**Comment by HELLspawnTIM** [comment] 2016-08-12 07:23
Got 3 BOTs running via 3 different proxies
All experience issues now

One of them can catch pokemon, but can not farm pokestops
The other two can't catch pokemon and can't farm pokestops

All of them have been running through TimeSquare for days with 300km/h  :-)

**Comment by gummyruler** [comment] 2016-08-12 07:23
@Elvete ahahahaha 

![oh you](https://cloud.githubusercontent.com/assets/20757587/17615399/4f1c6e58-602b-11e6-8e9f-6182006441c4.jpg)

**Comment by gummyruler** [comment] 2016-08-12 07:23
@HELLspawnTIM Speed of light!!

**Comment by joy0824** [comment] 2016-08-12 07:23
300! OMFG

**Comment by Thikez** [comment] 2016-08-12 07:24
He's like riding a ferrari with no traffic

**Comment by gummyruler** [comment] 2016-08-12 07:24
I ran mine 3000 once. So I can't really judge.

**Comment by PokePro21** [comment] 2016-08-12 07:24
@gummyruler okay ! I thought you are indian

**Comment by gummyruler** [comment] 2016-08-12 07:25
@PokePro21 I was, until I was reborn. Praise Cthulhu !!

**Comment by monchen** [comment] 2016-08-12 07:25
http://www.mmoserverstatus.com/pokemon_go

**Comment by mosty1982** [comment] 2016-08-12 07:27
rip my account i was able to take down lvl +8 gymes alone :'(((

**Comment by Elvete** [comment] 2016-08-12 07:27
AHAHAHA now i know why i am ine in the game... ROMANIAN servers are up LOL xD <3 Romania nice country

**Comment by gummyruler** [comment] 2016-08-12 07:27
@Elvete All HAIL Michael I!!!

**Comment by HELLspawnTIM** [comment] 2016-08-12 07:28
@monchen
It says GERMANY = 31min
But I can login to 4 different Google Accounts in PokemonGO in 2sec fine
Site is bullshit or only applies to PTC Accounts

**Comment by joy0824** [comment] 2016-08-12 07:28
nope...mine still one up and one down, i login with same device taking turn with different account. rip dragonite

**Comment by joy0824** [comment] 2016-08-12 07:28
i want more friends.. :(
the bot is fine

**Comment by untesty** [comment] 2016-08-12 07:28
I'm in Belgium and all servers are up

**Comment by HELLspawnTIM** [comment] 2016-08-12 07:28
@joy0824 
FUCK YOU FUCKING DRAGONITE ALREADY
STOP SAYING THAT

**Comment by Elvete** [comment] 2016-08-12 07:28
ARE SERVERS FFS..look romania have nos erver isues and i cna login in the game so...

**Comment by monchen** [comment] 2016-08-12 07:28
if its permaban then u cannot log in anymore. server is just DOWN

**Comment by lovakosh** [comment] 2016-08-12 07:29
Does any one tried to use pokestop's via Nox or phone? I got on every pokestop "try again later"

**Comment by HELLspawnTIM** [comment] 2016-08-12 07:29
Thank god i did never botting with my real account ...
Only used it to power-up 3 fake accounts

**Comment by HELLspawnTIM** [comment] 2016-08-12 07:30
@lovakosh
Same for my 3 BOTs

**Comment by Elvete** [comment] 2016-08-12 07:32
GUYS..Read my opinion pls...ur not permabanned...they just changed the way that sotbans work...that u wont be able 2 unban yoursel by spining the same pokestop 40 times..i u can pick the pokestop u wont be able 2 spin it 39 more times...so u wont be able 2 get unbanned..but they kept the pokemon thing..And for the people who cant login jsut look at the server status..they are fking down

**Comment by lailaps** [comment] 2016-08-12 07:32
No permaban. just ignore this panic threads. lol

**Comment by PokemonAddict** [comment] 2016-08-12 07:33
Can't find Pokestops with bot. Stopped it. Logged in with my phone... worked :) 
http://www.mmoserverstatus.com/pokemon_go => 43 min down in Germany :D

**Comment by PokemonAddict** [comment] 2016-08-12 07:33
Yeah but there is a difference between bot and phone ^^

**Comment by james741** [comment] 2016-08-12 07:33
@lailaps show me ur source

**Comment by lailaps** [comment] 2016-08-12 07:35
I noticed it some hous ago with one of my accounts.
Tried it again after 3 hours and it is working again.
The accounts which are still used bots are disconnected since maybe one hour and I will try it in 2 hours again, to check...

**Comment by HELLspawnTIM** [comment] 2016-08-12 07:35
@PokemonAddict
43min = GERMANY is bullshit
I can login two 4 different Google Accounts within 2sec fine
Either the site is bullshit or only applies to PTC accounts

**Comment by Khorajuste** [comment] 2016-08-12 07:37
work on plateform:
Vanilla: android not work/IOS  not work/NOX  not work
Bot: android  not work/ios WORK/ nox  not work

probably some random on the connection  :/

**Comment by Khorajuste** [comment] 2016-08-12 07:39
![lol](https://cloud.githubusercontent.com/assets/20834027/17615766/94cd7218-6070-11e6-8039-bfcaeb56162d.PNG)
dont panic ....
upgrade this night 11 august ...

**Comment by lailaps** [comment] 2016-08-12 07:40
Can someone close this useless panic thread...
Just another kind of block / softban...
https://github.com/Ar1i/PokemonGo-Bot/issues/3065

**Comment by Polarbear008** [comment] 2016-08-12 07:41
#3073

**Comment by james741** [comment] 2016-08-12 07:48
@lailaps why u wan me close so bad.
wait till someone tell me whats really going on and with the right source

**Comment by Elvete** [comment] 2016-08-12 07:49
Resolve : https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by PokemonAddict** [comment] 2016-08-12 07:50
@Elvete nooooot :dancer:

**Comment by AiVo7z** [comment] 2016-08-12 07:51
This has happened to me likewise. wait a couple hours or even a day and it solves itaelf. had exactly the same. still no perma ban now

**Comment by Biscuit090** [comment] 2016-08-12 07:51
Don't click that shit just anot her cancerous troll song

**Comment by kickz** [comment] 2016-08-12 07:52
Servers are down see on this status: https://p.datadoghq.com/sb/1xfifX-a17f211ecb?tv_mode=true

**Comment by james741** [comment] 2016-08-12 07:56
@lailaps since you say this is a new way of getting solf-ban. 
I going to wait and see how it go and going to update here myself. 
For now i going to leave this post on.

**Comment by Kaluminatie** [comment] 2016-08-12 07:57
US Google/PTC servers currently down, no permaban at all. Check link below.

http://ispokemongodownornot.com/

**Comment by Georgiexoh** [comment] 2016-08-12 07:59
So even if I get failed to retreive data from server, it is no permaban, but is a softban>>?

**Comment by Elvete** [comment] 2016-08-12 08:00
PROblem resolve  https://www.youtube.com/watch?v=vfc42Pb5RA8

**Comment by blasanru** [comment] 2016-08-12 08:01
Not issues from servers....cause i can log in with another account (no bot) and with my account (bot) i cant.... both google

**Comment by gummyruler** [comment] 2016-08-12 08:03
Bot is running 100%

![no problemo](https://cloud.githubusercontent.com/assets/20757587/17616263/dac5190a-6030-11e6-80cc-69b9322e1661.png)

**Comment by xuban** [comment] 2016-08-12 08:03
Useless cry thread.
Close this and dont alarm.

Servers has connection problems
http://www.mmoserverstatus.com/pokemon_go

**Comment by james741** [comment] 2016-08-12 08:03
@gummyruler  i never say bot is down

**Comment by gummyruler** [comment] 2016-08-12 08:09
@james741 Your accounts might just be undergoing some regional freeze or something. Where do you guys live though?

**Comment by Kidnub** [comment] 2016-08-12 08:09
How i bot: 
google account
daily botting about 8~12h 
Speed 10km/h 
i dont know how much exp in a hour XD
Lvl XX <-- GG

i can use my accounts XD next before all say ban ban ban ban ban ban use once a little bit a breain... google login has since 2 days big login issue again ... 
next if you use the bot  with too much speed normal that they see u use a bot XD
thats why i never move over 10KM/H .... why i need to rush the bot if he can do it easy peasy

**Comment by Yotumn** [comment] 2016-08-12 08:12
I have to come back on my previou confirmation of ban, my bot account was just granted access, now my non-bot account has the issue.. Seems unstable servers are the cause.

Everything will be fine, in the meantime you can all have a life for a few hours :) HAPPY LIVING ^^

**Comment by Kidnub** [comment] 2016-08-12 08:13
so pls close it here then ...... i dont know why ppl so scared about an bot account ... my major account is clean played and even rank 25 XD in 14 days real move XD i hope in next time the poketransfairs are coming

**Comment by rvonz** [comment] 2016-08-12 08:16
i have 3 (bot) account google, and everything can be accessed
what's the problem?

**Comment by xuban** [comment] 2016-08-12 08:19
@rvonz the issue is there are a lot of Kids was discovered github and post threads to cry.

**Comment by Elvete** [comment] 2016-08-12 08:26
#3074

**Comment by renan-masse** [comment] 2016-08-12 08:26
I'm from France ; France : 151ms
Can't loggin, same error can't grab data.
Something happen.

**Comment by gummyruler** [comment] 2016-08-12 08:27
Works perfectly well in the US.

**Comment by gummyruler** [comment] 2016-08-12 08:27
Just wait it out. It's the price of people using 100 bots at the same time.

**Comment by Bastii1988** [comment] 2016-08-12 08:36
Got this error "failed to retreive data from server" in my bot-account (Google, location germany/eu) for 8 hours. My other account (google) where i didn't used a bot works fine.

**Comment by Bastii1988** [comment] 2016-08-12 08:36
So I think everyone who gets this error got a permanent-ban now...

**Comment by blasanru** [comment] 2016-08-12 08:43
@Bastii1988 Same!!!! It seems a perman ban...

**Comment by blasanru** [comment] 2016-08-12 08:57
WTF? https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308

**Comment by xuban** [comment] 2016-08-12 09:01
This form exist form first day. 
STOP TROLLING AND WAIT SERVER AND LOGIN OK STATUS

**Closed** 2016-08-12 09:21 UTC
