### ISSUE TITLE
[Bug] Transferring bug is still there

### ISSUE THREAD

**Issue by PokePro21** [Ar1i/PokemonGo-Bot#2705] opened 2016-08-10 19:31 UTC
Its not transferring pokemon even it is in low CP & IV .Even I selected Max Duplicate pokemons 2 its still keeping more than 2+
Even the mankey is low in Cp & IV also it doesnt tranfer it it happens with lots of pokemons
![11111untitled](https://cloud.githubusercontent.com/assets/20843400/17567928/01edf736-5f5f-11e6-8bbb-d60b351ecbab.png)

**Comment by pokerave** [comment] 2016-08-10 19:32
show settings.

**Comment by Hydro420** [comment] 2016-08-10 19:33
You are not letting the bot have a chance to do so - Running it too fast while catching and hitting pokestops prevents it from transferring.. It transfers when heading back to original destination or when nothing is around for the bot to catch or pokestops to hit.. Ive kept a close eye on this...

**Comment by PokePro21** [comment] 2016-08-10 19:33
![01](https://cloud.githubusercontent.com/assets/20843400/17568029/7994dce6-5f5f-11e6-8bcf-1340fb70bb76.png)

**Comment by pokerave** [comment] 2016-08-10 19:34
im thinking more like refresh not check or IV and CP setting.

**Comment by kazzaluis** [comment] 2016-08-10 19:34
same problem release charmander 36 ivs and keep a 17 ivs

**Comment by pokerave** [comment] 2016-08-10 19:34
uncheck TransferFirstLowIV

**Comment by kazzaluis** [comment] 2016-08-10 19:34
Latest Build - 10.08 21.22.rar

**Comment by Hydro420** [comment] 2016-08-10 19:36
My settings are same as his and no problem here.

![4](https://cloud.githubusercontent.com/assets/20824888/17568081/c1746c5a-5f07-11e6-9ae5-eb834ba2c23a.png)

**Comment by PokePro21** [comment] 2016-08-10 19:36
i didnt done anything its just not  transferring some times @Hydro420 .

**Comment by emilie253** [comment] 2016-08-10 19:37
same for me ... transfert my best IVs..

**Comment by PokePro21** [comment] 2016-08-10 19:37
actually there is still bug @Ar1i please check

**Comment by pokemav** [comment] 2016-08-10 19:37
I've seen it before and I dont think it's a bug. Maybe you dont know how it works. 
Behaviour is as intended. You will keep any pokemon above 85% or 800 CP no matter what. 
AND you will KEEP max 2 of each that DO NOT MATCH 85% 800 CP! So if you catch another mankey below those values you will keep it again, but only 2 of them as you set 2 as MAX.
GET IT?

**Comment by emilie253** [comment] 2016-08-10 19:39
for me it works like that : you keep 2 (90% IVS or 800 cp per exemple) after you keep two another : 

35%---36cp
50%--- 800 cp
70 %-- 500 cp.

for me you transfert 35% and not 70% ! but the bot transfert 70 %..

**Comment by Hydro420** [comment] 2016-08-10 19:42
You notice how it works when the bot has nothing else to do? Stop running it so fast or just wait for the bot to free up a bit. Third option is to manually do it (best option in my opinion, as you get to keep exactly what you want)

![4](https://cloud.githubusercontent.com/assets/20824888/17568237/896c85c6-5f08-11e6-8277-409a1aaeb10f.png)

**Comment by pokerave** [comment] 2016-08-10 19:42
DID YOU UNCHECK THIS? 
![transferfirstlowiv](https://cloud.githubusercontent.com/assets/20603254/17568256/b5fa60e8-5f4b-11e6-99dc-55c0c7035a46.png)

**Comment by pokemav** [comment] 2016-08-10 19:43
emilie253 the bot transfers the lower CP, not the lowest IVs, that's how it works now. Because IVs are not as important (only 10%) improvement if you get a 100% pokemon instead of a 10% IV Pokemon. So by transfering the lowest CP it saves up candy if you wanna level up your pokemon.

**Comment by Hydro420** [comment] 2016-08-10 19:44
^No - IV is way more important than CP

**Comment by pokemav** [comment] 2016-08-10 19:44
Only 10% improvement, not a big deal, but a nice to have.

**Comment by emilie253** [comment] 2016-08-10 19:45
my english is bad, but for me "transferfirstlowIV" = transfert at first monstres with low IV" so, you transfert 35% before 70%.

cp is usuless for good monster, iv is very important

**Comment by Hydro420** [comment] 2016-08-10 19:45
10%? how do you figure? I have a 21 IV with lets say 3-2-5   where as the 90 IV is 11-11-15 lets say

**Comment by pokerave** [comment] 2016-08-10 19:45
CHECK ALSO SETTING FOR BOTH
![with delay](https://cloud.githubusercontent.com/assets/20603254/17568383/339a1994-5f4c-11e6-9ef8-d1e177de3aaf.png)

**Comment by emilie253** [comment] 2016-08-10 19:46
@pokerave i want transfert low ivs at first x) ^^

**Comment by pokemav** [comment] 2016-08-10 19:46
the game doesnt take into account IV as much as gameboy versions. 
 You can read that here https://thesilphroad.com/research at IV RATER

**Comment by Hydro420** [comment] 2016-08-10 19:47
Not yet it doesn't

**Comment by emilie253** [comment] 2016-08-10 19:48
@pokerave  so, for you, a charmender with 5% is same than charmender with 95% ?

**Comment by Hydro420** [comment] 2016-08-10 19:49
@emilie253 apparently

**Comment by pokemav** [comment] 2016-08-10 19:50
from a performance standpoint it's better to have a 1800 CP pokemon with 20%IV than a 18 CP with 100% because it'll cost you so much stardust and candies to level it up to 1800CP. Probably hundreds of candies and over 100k stardust. So if you wanna save those, keep an eye on them. It depends on what you want in the long run. I usually wait for a high CP and high IV and transfer the very low CP's with high IVs. its not worth it to spend so much on them. Maybe a dragonite would.

**Comment by emilie253** [comment] 2016-08-10 19:51
cost so much yes, but finaly, you have best pokemon with 18CP and 100%.

**Comment by pokemav** [comment] 2016-08-10 19:55
You know what 10% improvement means? Pokemon go attacks damage for fast attacks do about 12 damage points. 10% would be lets say 12.12 damage. Imagine you fight an snorlax with 200 HP. You would only damage .12 HP more.  Im not saying it's not good but not a big deal yet. A fight between 2 same pokemons at same CP and different IV should be even in the end. dont expect it to have twice as HP or twice damage points or twice defense.

**Comment by emilie253** [comment] 2016-08-10 19:57
yes but if the bot takes 1000 cp with 50% and transfert 50 cp with 90 %.... it's 40 % and not 10% ...

**Comment by pokemav** [comment] 2016-08-10 20:00
ok, you're not getting it. 10% total. that means that a pokemon with 0% IVS vs a 100% IVS is only 10% stronger. not 100% stronger or 40% as you say. Because in pokemon go ivs were not meant to matter as much as in gameboy etc.

**Comment by pokerave** [comment] 2016-08-10 20:02
@emilie253  YES I want to keep HIGHER IV's too. but for now the bot is not doing that. so uncheck it so it can transfer normally.

@pokemav YES HIGHER CP is Better with HIGH IV LOW CP (FOR BEGINNING) **BUT** 

A Caterpie with 5%IV will  MAX its CP lower than a Caterpie with a HIGH IV in the long run. (see IV A-D-S[ATTACK-DEFENSE-STAMINA])check this you have a 
caterpie with 5% IV 5A-5D-5S you will defeat 
caterpie with 100%IV with 15A-15D-15S easily?

YES LOW CP IVs will take a lot of Dust and candies but its worth it.. BTW CHECK this with what you have same level
![100iv](https://cloud.githubusercontent.com/assets/20603254/17568891/698b4a80-5f4e-11e6-94e6-d4b5ee0ce4c6.jpg)

**Comment by emilie253** [comment] 2016-08-10 20:05
woooo i need your dratini x) where you farm? SF? x)

**Comment by jmo93** [comment] 2016-08-10 20:43
two questions: @Hydro420  what is PC Miler for? 

what is the Telegram Settings for?

**Comment by Spartacusbr** [comment] 2016-08-10 20:50
@jmo93 Great question, to this date I'm clueless of what that is supposed to do!

**Comment by UserWest** [comment] 2016-08-10 20:54
@pokerave I don't mean to get off topic, but can you share the location you use to farm dratini?

**Comment by pwnjke** [comment] 2016-08-10 21:05
bei mir verschickt der Bot auf solche Weise ziemlich viele pokemons. ich überlege schon ob ich die transfer funktion ausschalte xD
![untitled](https://cloud.githubusercontent.com/assets/20947780/17570954/bcb65240-5f4e-11e6-872e-b1c62e4b1021.png)

**Comment by pokemav** [comment] 2016-08-10 21:34
I'll say it again, it's not a bug. Maybe you dont know how it works. 
Behaviour is as intended. You will keep any pokemon above 85% or 800 CP no matter what. 
AND you will KEEP max 2 of each that DO NOT MATCH 85% 800 CP! So if you catch another mankey below those values you will keep it again, but only 2 of them as you set 2 as MAX.
GET IT? If you raise the limit to say 94% and 800 CP, it'll transfer 1 because none match the DO NOT TRANSFER values.

**Comment by pokemav** [comment] 2016-08-10 21:35
@emilie253 I already told you. 10% it's already known. Check this website https://thesilphroad.com/research#monRater and READ

**Comment by starscream151** [comment] 2016-08-10 21:38
maybe it's because you ticked this? try to untick it?
![ucheeckntitled](https://cloud.githubusercontent.com/assets/20950801/17572095/26d983b2-5f7d-11e6-88dc-9e1ea1beec6d.png)

**Comment by NaveTK** [comment] 2016-08-10 21:44
IV's are more important in the endgame. For example, a Dragonite will have 3500CP when it's fully maxed out with 100% IVs, but it will only have 3067CP at 0% IVs... that's almost 500CP, that's not a "minor" difference, it's huge... 
my goal is it to own the 10 highest CP Pokemon with 100% IVs to have the strongest and most stylish team possible

**Comment by ciberfuturo** [comment] 2016-08-10 21:50
I had the same problem. With in observation of "starscream 151" the problem is solved. TY

**Comment by elenex23** [comment] 2016-08-10 22:41
@pokemav just stop. iv > cp its very basic knowledge. cp is based off of iv so how could cp ever be more important? Don't answer it was rhetorical. I just wish we had some clarity on the subject.

**Comment by bboylost** [comment] 2016-08-10 23:01
uncheck the "keep pokemon which can be evolved... check setting before you post anything stupid...the bot works perfectly fine with the transfer

**Comment by PokePro21** [comment] 2016-08-11 07:39
@bboylost  really are you sure or you are not observing it

**Comment by chusski** [comment] 2016-08-11 08:21
@Ar1i I Think know where are the problem:

If active "TransferFristLowIV" and have saved pokemon (from Max. IV to transfer) them compare with it and all ok. But if dont have pokemon saved (from Max. IV to transfer) them compare with same pokemon and transfer it.
The problem are when comparation

EXAMPLE:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 50% (Best: XXX CP, IV 90%)

Them transder all its ok.

BUT:

TransferFristLowIV: ON
Max. IV to transfer 90%: ON ( have on stock a Abra CP XXX IV 80% or other low that 90% )

Catch: Abra CP XXX IV 50% 
Transfer Abra CP XXX IV 80% (Best: XXX CP, IV 80%)

Them transfer the more higer you have.

Sorry for my poor english i think example can help to understand my.

Thx very much for all your hard work ^^

**Comment by Abbasoo** [comment] 2016-08-11 08:56
Use PokeBot v4.2
It has the same UI.

**Comment by w19ten** [comment] 2016-08-11 09:04
This is a good bot and good piece of work.
Well, naming on the option may need a bit of fine touch, so people may get it better.

**Comment by PureDizzi** [comment] 2016-08-11 09:40
Pokemon should be transferred lowest to highest. It should be simple to implement. If you need help, hook me up! Also, an awesome feature to include is accounting for movesets. If we could also have highest IV for each moveset, that would be insane! That also is not hard to implement. You have already obtained the data.

**Comment by DirtyAssign** [comment] 2016-08-11 11:16
Hi at all,
this is for me a error. Or do i have a wrong configuration? 
![transfer_error_transfer_stronger_pokemon](https://cloud.githubusercontent.com/assets/20907595/17587018/b669adac-5fc5-11e6-9a5a-312d35a17cb2.png)

**Comment by Ar1i** [comment] 2016-08-11 11:28
redownload newest version

**Closed by Ar1i** 2016-08-11 11:28 UTC
Labels: major bug
