### ISSUE TITLE
Adding lure w/o having it enabled

### ISSUE THREAD

**Issue by k0ut4li4n0s** [Ar1i/PokemonGo-Bot#3504] opened 2016-09-01 11:09 UTC
As i say to the title, i ve setted the walk time etc but didnt set it to add lure when break, just to break on lured pokestop(does that mean that if its not lured it will auto lure ? ) 

![12345](https://cloud.githubusercontent.com/assets/21258333/18165384/a44dbd0a-704d-11e6-9e00-6ba0f8be2733.png)

**Comment by MTK4355** [comment] 2016-09-01 12:29
nope, that's a bug. I'll look into it. sorry for wasting your lure!

**Comment by Kidnub** [comment] 2016-09-01 12:40
I hade the same problem and the bot wont move until the lure is over ;( but nice work even if i lose two lure s XD Awesome

**Comment by Hydro420** [comment] 2016-09-01 13:02
@MTK4355 - The new update is freakin awesome!!! Thanks DEVs! CHEERS

**Comment by Kidnub** [comment] 2016-09-01 13:18
but now i ll stop the but until the bug is fix i losed the thrid lure
XD i hope it will not be to long but even if it takes some time i can wait np XD

**Comment by Hydro420** [comment] 2016-09-01 13:25
Try un-checking the options to break at lure, etc. and run the bot?

**Comment by jmo93** [comment] 2016-09-01 13:28
If i manually pause walking, the bot also activate a lure.

**Comment by Hydro420** [comment] 2016-09-01 13:30
Yea, kind of a bummer but I dont mind at all... The devs will get to work on it and fix it.. Free is free and I will not complain lol.

**Comment by Tr1n0va** [comment] 2016-09-01 13:32
And if the bot stops at a lure pokestop, it said do stop 7,35 minutes or so, but it wont be move again...

i wait for at least 30 minutes....

**Comment by jmo93** [comment] 2016-09-01 13:32
Yeah I am thankfull for this bot!
Thanks  to the devs.

**Comment by Hydro420** [comment] 2016-09-01 13:32
Mine moved, then it stopped for 7min at next lure.

**Comment by Hydro420** [comment] 2016-09-01 13:33
Mine started walking again then stopped at the next lure for 7min

**Comment by Hydro420** [comment] 2016-09-01 13:34
By the way - when bot stopped at second stop, it did not use a lure. ( i got 5 left)

**Comment by MTK4355** [comment] 2016-09-01 15:53
So, the issue is that the checkbox values default to a checked value even though it appears unchecked in the GUI. Until my next pull is submitted and built the workaround is to check and uncheck any values you do not want to use. That way you are positively setting an unchecked state the bot will respect when it runs. 

Make sense?

**Comment by MTK4355** [comment] 2016-09-01 15:54
Only using 1 lure per run is intentional to avoid using all of your lures in one session. It will only use one at the first break.

**Comment by MTK4355** [comment] 2016-09-01 15:58
If you get stuck on break, toggle the "Pause Walking" button in the Pokémon GUI to get moving again. I knew about that sometimes sticking when I committed the features, but figured you guys wanted to start using the features more than you wanted absolute perfection. :) Check out the comment on my pull request for a few other known issues: https://github.com/Ar1i/PokemonGo-Bot/pull/3497

**Comment by Hydro420** [comment] 2016-09-01 16:29
Def. would like the features vs absolute perfection (don't expect this at all) - this way you guys get trial n error tests as well ;-)

**Comment by deadelf0** [comment] 2016-09-01 22:38
Check and uncheck settings may work. These new setting are great this program is great, Thank you!

**Comment by deadelf0** [comment] 2016-09-01 23:22
Yeah, same the check settings for poke stops won't stick.

**Closed** 2016-09-17 19:36 UTC
