### ISSUE TITLE
cannot find pokestop within 5000m

### ISSUE THREAD

**Issue by MiGaBelG** [Ar1i/PokemonGo-Bot#2638] opened 2016-08-10 16:46 UTC
it won't find a pokestop even when im using a proxy

http://prntscr.com/c41cva

**Comment by stylized810** [comment] 2016-08-10 16:47
Haing same issue

**Comment by dcg121288** [comment] 2016-08-10 16:48
me too

**Comment by PokeProgress** [comment] 2016-08-10 16:48
same

**Comment by Ar1i** [comment] 2016-08-10 16:49
server sided probably http://www.mmoserverstatus.com/pokemon_go

**Comment by MiGaBelG** [comment] 2016-08-10 16:50
nope 154ms

**Comment by infslash** [comment] 2016-08-10 16:51
I got one instance with proxy and one instance without proxy running... all was fine until I started the second instance?
What kind of anti-botting mechanism is this?

**Comment by xxKevinSniperxx** [comment] 2016-08-10 16:54
This issue is caused by either server issues or an ip ban.

**Comment by MiGaBelG** [comment] 2016-08-10 16:54
Guys ! restart the bot and it'll work

**Comment by infslash** [comment] 2016-08-10 16:54
Why do you close this when it doesnt fix it?! omg

**Comment by infslash** [comment] 2016-08-10 16:55
@Ar1i

**Comment by MiGaBelG** [comment] 2016-08-10 16:55
it's fixed for me :) i just restarted the bot a few times it was the server...

**Comment by infslash** [comment] 2016-08-10 16:56
Nope, not true. The bot restarts itself and it doesnt work. Like I described...

**Comment by xxKevinSniperxx** [comment] 2016-08-10 16:57
just wait a minute, the issue will be back @MiGaBelG

**Comment by bboylost** [comment] 2016-08-10 16:58
Really Thank you for all the hardworks, Ar1i!  

Just one question would like to ask, Can I use 2- 3 accounts while using different proxy on each bot?

Or I can only use one account on one computer but the proxy is just for in case you get banned?

Thank you!

**Comment by dhiw** [comment] 2016-08-10 16:59
Mates! dont run the bot twice or more on the same IP Adress ! Just Reboot your Router (New IP) and use only 1 Account. This Issue comes only when you are running more than 2 Accnts

**Comment by infslash** [comment] 2016-08-10 17:00
Can't u read properly? I described: I got one instance with proxy and one instance without proxy running... all was fine until I started the second instance?
What kind of anti-botting mechanism is this?

**Comment by infslash** [comment] 2016-08-10 17:00
@dhiw

**Comment by xxKevinSniperxx** [comment] 2016-08-10 17:00
@bboylost if you run more than 3 bots your ip will probably get banned which will cause this issue

**Comment by xxKevinSniperxx** [comment] 2016-08-10 17:02
@infslash Niantic added a new soft ban into pokemon, its called a ip banned, Niantic uses it to stop bot users, or at least slow them down.

**Comment by jeremie152** [comment] 2016-08-10 17:02
more than 2 bots.

**Comment by jeremie152** [comment] 2016-08-10 17:03
only one instance for dont get a ban

**Comment by infslash** [comment] 2016-08-10 17:08
But I use one bot with proxy and one without.... why is that so?! @xxKevinSniperxx

**Comment by jeremie152** [comment] 2016-08-10 17:10
proxy dont work

**Comment by jeremie152** [comment] 2016-08-10 17:10
i have banned 2 bot with proxy^^

**Comment by Zixey13** [comment] 2016-08-10 17:10
run CMD
type:  ipconfig /release
type: ipconfig /renew
switch off modem and pc for 2-3 minutes
then switch on
start bot

it will work

**Comment by infslash** [comment] 2016-08-10 17:11
why does the other instance without proxy not work anymore? I just started the second with proxy... is this so hard to read?

**Comment by xxKevinSniperxx** [comment] 2016-08-10 17:13
@infslash it doesn't matter if you're only running one bot, your ip can still be banned. confused then read this for a better understanding http://www.se7ensins.com/forums/threads/tutorial-ip-banned-heres-your-solution.1548353/

**Comment by bboylost** [comment] 2016-08-10 17:14
Yea, in theory though, one bot with proxy and one bot without (using your real IP) should work?

2 bots in total, I tested it , it doesnt work. haha

Someone correct me if i am wrong ?

**Comment by infslash** [comment] 2016-08-10 17:16
same here @bboylost 
That's what I'm asking about all the time............

**Comment by xRealMaks** [comment] 2016-08-10 17:17
Its a server issue.

**Closed** 2016-08-10 17:17 UTC

**Comment by bboylost** [comment] 2016-08-10 17:19
@infslash Yea i understand what you meant , but some dont and just comment lol.  anyway , lets test it out ourselves !

**Comment by xxKevinSniperxx** [comment] 2016-08-10 17:21
this is why you can get an ip ban. "It has come to my attention that Niantic is handing out IP bans for people using excessive amounts of bots on one IP address. This happens because the bot keeps spamming request API for actions for the bot. One way to avoid this is to use less than 4 bots at once, but for some, including myself, it's too late for that." (quote taken from: http://www.se7ensins.com/forums/threads/tutorial-ip-banned-heres-your-solution.1548353/ )
