### ISSUE TITLE
* INFORMATION * READ

### ISSUE THREAD

**Issue by Ar1i** [Ar1i/PokemonGo-Bot#1274] opened 2016-08-04 09:09 UTC
If, we are updating. I will push only the executeable out. Cause someone is still stealing it. Soo he get some problems, cause he never can get it to work. 

Btw. i got the exact thing which needs to be fixed. And got a clue about how. Probably happening today or tomorrow. 

If you can Code orso, you can take a look at the decompiled Pokemon APK. http://ar1i.xyz/download/

**Comment by Ozymumbles1** [comment] 2016-08-04 09:13
The PokeStops currently don't show.

**Comment by motemo77** [comment] 2016-08-04 09:14
@Ozymumbles1 no shit, sherlock!

**Comment by FoolYah** [comment] 2016-08-04 09:14
Take your Time! <3 But idk how to code so yeah ^^ :smile:

**Comment by SELECTIONNN** [comment] 2016-08-04 09:14
Sick af dude, u can get it!

**Comment by Maybones** [comment] 2016-08-04 09:15
Good Luck

**Comment by Ozymumbles1** [comment] 2016-08-04 09:15
I'm so clever, Be Jealous. :$

**Comment by Maybones** [comment] 2016-08-04 09:16
I Can Help You

**Comment by Jam1ePistol** [comment] 2016-08-04 09:16
> If, we are updating. I will push only the executeable out.

Since i am a total noob , what exactly does that mean :P

**Comment by Polarbear008** [comment] 2016-08-04 09:17
good luck Ar1i

**Comment by bunnymuny** [comment] 2016-08-04 09:18
Basically there is a person stealing the copilation of Ar1i and he doesnt know how to fix the whole issue that why he ill push out only the executeable.

**Comment by 0x92** [comment] 2016-08-04 09:18
Since i cant program C# and cant contribute anything i post memes for support 
![abk50vo_460s_v2](https://cloud.githubusercontent.com/assets/6593435/17396734/05dfb8f4-5a35-11e6-82e1-47265d6dce67.jpg) how does it feel to be "famous"?

**Comment by jief78** [comment] 2016-08-04 09:19
@Jam1ePistol since we're noob this doesn't change anything for us

**Comment by HaydarOzturk** [comment] 2016-08-04 09:20
@Jam1ePistol thats mean there will be no source code update so improvement of this program will be slower because a lot of programmer couldn't make conturbution trough git-hub without seeing the source code. But the best part is no one can steal the main code again if they fail to manage the fix the mistake bythemselves... At least I gues this is all about :)

**Comment by 0x92** [comment] 2016-08-04 09:25
@HaydarOzturk  yeah but the vitnamesian fagget who sells this bot and claims to be the programer of it should be removed permanently from the internet. 
![eb760446ceca49ad](https://cloud.githubusercontent.com/assets/6593435/17396967/1df29ae6-5a36-11e6-8804-69ff3b61fe20.jpg)

**Comment by eLDeMe** [comment] 2016-08-04 09:27
I'm checking the code coz is java but I don't know what to look for, I'm new at this (I know to code only java and trying to learn other languages)

**Comment by HaydarOzturk** [comment] 2016-08-04 09:27
@0x92 That's right but he is not the only one who is messing with the source code. I even encounter some people in my country so the best way to prevent this closing the source code for public access. I think Ar1i should build up his own team trough trust. I wish I could code in a proffesinioal way but people who can code should help...

**Comment by mastercoyin** [comment] 2016-08-04 09:29
@Ar1i hei it first i will use origin bot,can you give me tutor how to use this bot? Cause i always use bot from pokecrot indonesia and im indonesian

**Comment by bunnymuny** [comment] 2016-08-04 09:29
@mastercoyin lol you made my day ......

**Comment by mastercoyin** [comment] 2016-08-04 09:30
Wkwk i cant speak english :v

**Comment by motemo77** [comment] 2016-08-04 09:32
@mastercoyin ... wow... just wow...

**Comment by bunnymuny** [comment] 2016-08-04 09:32
@mastercoyin The problem is you was using a copied bot from Ar1i team and now you`re asking to the owner to show you how to use his own bot lol. You definitely made my day

**Comment by jief78** [comment] 2016-08-04 09:33
@mastercoyin POKECROT IS A THIEF he steal the source from here

**Comment by mastercoyin** [comment] 2016-08-04 09:34
Dont blame to me,if you want you can blame to who copied from ar1i -_-

**Comment by motemo77** [comment] 2016-08-04 09:34
@mastercoyin be more resourceful next time, dude...

**Comment by HExxitGEarHD** [comment] 2016-08-04 09:34
@Ar1i   I have read niantic api has changed nobody can hack or which can use to the example offered. gps fly

**Comment by mastercoyin** [comment] 2016-08-04 09:35
I just user ,and last day i dunno if pokecrot stealing from ar1i

**Comment by bunnymuny** [comment] 2016-08-04 09:36
@HaydarOzturk Don`t say nobody cause everything in this life is hackeable even the Microsoft corporation center :DDD

**Comment by SELECTIONNN** [comment] 2016-08-04 09:36
Never say never

**Comment by motemo77** [comment] 2016-08-04 09:37
For greater good! let it be hacked!
power to the people!

**Comment by LvGPoke** [comment] 2016-08-04 09:39
@Ar1i  THE KING IN THE NORTH!

**Comment by HaydarOzturk** [comment] 2016-08-04 09:40
@bunnymuny niantic should hacked not Ar1i :D

**Comment by bunnymuny** [comment] 2016-08-04 09:44
Let`s give to Ar1i time to work on the issue, everything will be fine till saturday ;)

and now guys enjoy life while devs are working on fixing the bot :D

**Comment by HaydarOzturk** [comment] 2016-08-04 09:45
@bunnymuny that sound cruel I don't wanna enjoy if they can'ttt

**Comment by motemo77** [comment] 2016-08-04 09:46
@HaydarOzturk give some thoughts and prayers to the devs... and some donation of course...

**Comment by bunnymuny** [comment] 2016-08-04 09:46
Well they enjoy developing as much as you eating an ice- cream

**Comment by HaydarOzturk** [comment] 2016-08-04 09:47
I enjoy developing too but I can't. I am the victim here :D

**Comment by FoolYah** [comment] 2016-08-04 09:59
https://cracked-games.org/pokemon-go-bot-software-pokecrot/ this looks stolen too

**Comment by eblebleh** [comment] 2016-08-04 10:06
the owner of pokecrot cant fix the bot he start to sell pogo accounts on facebook :v

**Comment by Ar1i** [comment] 2016-08-04 10:07
@eblebleh +1

**Comment by HaydarOzturk** [comment] 2016-08-04 10:08
@eblebleh not even RIP. RIHell fucktard

**Comment by bunnymuny** [comment] 2016-08-04 10:08
i don`t like people who steal the work of others and get paid for it lol

**Comment by mastercoyin** [comment] 2016-08-04 10:09
@eblebleh yeah i saw to wkwk his name messa :v

**Comment by OhhPian** [comment] 2016-08-04 10:10
@eblebleh can i get the link ? hahahahaha

**Comment by 0x92** [comment] 2016-08-04 10:10
@eblebleh give me his fb profile i make some memes about him

**Comment by bunnymuny** [comment] 2016-08-04 10:10
btw probably he`s now reading us on this thread :DDDDDDDDDDD

salute my stealer friend

**Comment by kiransonavana007** [comment] 2016-08-04 10:10
![bot error](https://cloud.githubusercontent.com/assets/20353772/17398318/cac0ec6e-5a59-11e6-9aa6-2610fb2242a7.png)
prob wht i do

**Comment by Tonyjaain** [comment] 2016-08-04 10:11
where is the best Pokemon farm spot for charizard, snorlax and blatusioe?

**Comment by mastercoyin** [comment] 2016-08-04 10:11
^zzzz

**Comment by pokerave** [comment] 2016-08-04 10:11
@kiransonavana007 wait for update.

**Comment by verybadboy85** [comment] 2016-08-04 10:12
Kann mir einer sagen oder zeigen nach was ich suchen muss in den Daten. Wie das ca auszusehen haben soll.

**Comment by mastercoyin** [comment] 2016-08-04 10:12
Still waiting :D

**Comment by pokerave** [comment] 2016-08-04 10:12
@Tonyjaain i got Snorlax and Blastoise from NY, I got Lapras from Boston

**Comment by bunnymuny** [comment] 2016-08-04 10:13
Guys lol i will explain it easy

1. Bot not working for now
2. In aprox 12/24h will be an update
3. Go and play pokemon go outside your house till the time 
4. Enjoy and don`t ask again why don`t work the bot l0l

**Comment by motemo77** [comment] 2016-08-04 10:13
@bunnymuny some people just....

**Comment by pokerave** [comment] 2016-08-04 10:14
I cant got out. its too hot.. im working in saudi arabia hahaha

**Comment by Tonyjaain** [comment] 2016-08-04 10:15
@pokerave at the central park in new yorK? and where in boston?

**Comment by keustii** [comment] 2016-08-04 10:15
Guys lol i will explain it easy

1. Bot not working for now
2. In aprox 12/24h will be an update
3. Install Nox
4. Enjoy and dont ask again why dont work the bot l0l

**Comment by LvGPoke** [comment] 2016-08-04 10:16
Why is the bot not working?

**Comment by pokerave** [comment] 2016-08-04 10:16
I dont like Bluestacks - TOO LAGGY and Nox - walk slow. lol

**Comment by HaydarOzturk** [comment] 2016-08-04 10:16
some steal the bot some steal the comment @keustii (Just a joke) But people are still asking unbelieveble...

**Comment by motemo77** [comment] 2016-08-04 10:17
@LvGPoke why is the bot not working? only God knows

**Comment by lamweixing** [comment] 2016-08-04 10:17
pokecrot... I think even their website design was stolen cuz if you go to /store you go to a fugly ass page lmao. hope they get sued or something

**Comment by pokerave** [comment] 2016-08-04 10:17
@LvGPoke Niantech updated the API used to read the Objects on the map. like the pokemon and the pokestop and the gyms. now the DEV of the bots need to reverse engineer the APP to get the API to work.

**Comment by LvGPoke** [comment] 2016-08-04 10:17
Haha it was a joke m8 ... saw your comment

**Comment by bunnymuny** [comment] 2016-08-04 10:18
For ppl w/0 knowledge about programing is like meeting jessica Alba in a Hotel room :DDD

**Comment by NevilleNg** [comment] 2016-08-04 10:18
@Ar1i good job bro.. i will wait your further noitice:)

**Comment by duyphuc1610** [comment] 2016-08-04 10:19
Good job, you really made my day

**Comment by Ozymumbles1** [comment] 2016-08-04 10:21
I officially hate Pokemon Go, I got the 400 Magikarp candies and evolved to Gyarados, and it just disappeared from everything, So pissed rn.

**Comment by lejoueuronline** [comment] 2016-08-04 10:21
Hello, the bot will be more functional at all for us? : /

**Comment by pokerave** [comment] 2016-08-04 10:22
well @bunnymuny i know VERY VERY Little about it. and i would still like to have Jessica Alba in a hotel room

**Comment by LvGPoke** [comment] 2016-08-04 10:22
I have 970 Magikarp candies xD so enough for 2

**Comment by pokerave** [comment] 2016-08-04 10:22
I have 2 Gyarados and 600+ magicarp candies. lol

**Comment by motemo77** [comment] 2016-08-04 10:23
@lejoueuronline ... no.. I hope not... I hope it only be functional to some players... I really do...

**Comment by waldiludi** [comment] 2016-08-04 10:23
http://www.mmoga.de/Pokmon-GO/Pokmon-GO-Account/
i am quite sure they are creating those accounts with your software and selling it. Not sure if thats legal

**Comment by Ozymumbles1** [comment] 2016-08-04 10:23
Lucky. 😂

**Comment by motemo77** [comment] 2016-08-04 10:24
best thread ever!

**Comment by LvGPoke** [comment] 2016-08-04 10:24
@waldiludi mmoga so unseriös ? Hätte ich nicht gedacht :(

**Comment by waldiludi** [comment] 2016-08-04 10:27
@LvGPoke hm bisher hatte ich auf mmogga noch nie probleme und hab auch immer in sie vertraut, aber das finde ich schon etwas unlegit...

**Comment by Shikkaku** [comment] 2016-08-04 10:28
ist es ueberhaupt moeglich 1,5M sternenstaub zu haben? lol (siehe mehr informationen)

**Comment by Provokan** [comment] 2016-08-04 10:32
Ja es ist möglich :)

**Comment by LucasK94** [comment] 2016-08-04 10:37
@Ar1i  Habe den Bot soweit gefixxt, kann man dich irgendwo Privat anschreiben? :)

**Comment by Provokan** [comment] 2016-08-04 10:38
@LucasK94 warum pullst du es nicht? :) Kannst ihn auf high-minded.net anschreiben er heißt dort raddat.

**Comment by Filip1232334** [comment] 2016-08-04 10:38
The PokeStops currently don't show. HOPE U FIX IT <3

**Comment by 0x92** [comment] 2016-08-04 10:40
@LucasK94  oder in Skype. Geh auf sein Githubprofil und dann auf seine URL dann siehste seine Skype ID

**Comment by Ar1i** [comment] 2016-08-04 10:41
@LucasK94 dann add mich mal auf Skype oario1998

**Comment by Provokan** [comment] 2016-08-04 10:41
ich glaube aber nicht dass er es fixxen konnte :) ist seid 4 tagen auf github ..^^

**Comment by LvGPoke** [comment] 2016-08-04 10:43
Und der Bot ist seit gestern down ... wieso sollte er es also nicht fixxen können ?

**Comment by Mrwaka27** [comment] 2016-08-04 10:43
If you need a more powerful server, hit me up!

**Comment by AKBlizzard** [comment] 2016-08-04 10:52
Just wondering if you have an eta on when the service will be back up. I would very much like to help if you need it, I can help in a few areas. PM me for help.

**Comment by Waiiim** [comment] 2016-08-04 10:55
ffs read the discussions before asking if the bot works or not yet

**Comment by NevilleNg** [comment] 2016-08-04 10:57
- DO NOT READ Before ASKING why BOT NOT WORKING - #1291

**Comment by kiransonavana007** [comment] 2016-08-04 10:58
hahahahahhaha

**Comment by tr1via1** [comment] 2016-08-04 11:06
lol

**Comment by yashmhatre** [comment] 2016-08-04 11:18
anyone know the co ordinates of drartini ???

**Comment by Ozymumbles1** [comment] 2016-08-04 11:19
Is it working again?

**Comment by Shikkaku** [comment] 2016-08-04 11:19
no

**Comment by Ozymumbles1** [comment] 2016-08-04 11:19
Oh, ok.

**Comment by xAzzzu** [comment] 2016-08-04 11:22
"If you decide to join the discord please read. I am not a programmer (disclaimer) but I saw the discord getting flooded by a lot of other non-programmers. Most of which were not helping the conversation and asking repeat-questions. I made a summary awnsering some repeat questions. And also as an update to the community.
SUMMARY
API stopped accepting requests from any sources which are not the actual client. The API needs a value "unknown 6", this value was already in the API in previous versions, but now the server is validating it. Only the actual client can create a valid "unknown6". We dont actually 100% know that it is indeed "unknown6" that is being validated, but it would make sense since its a big piece of data which isnt recreateable.
It is not as easy as locating where any updates made changes because the unknown6 was already being calculated and sent in previous versions but not validated by the server.
It doesnt really matter exactly what values go into the unknown6. CRACKING/bruteforcing the code is impossible because the key alone wouldnt do it. We need to get to the piece of code that makes "unknown6". The key and the way to calculate unknown6 is somewhere within the code and were trying to find it.
We are trying to locate where the app calculates unknown6 in order to be able to recreate out own valid unknown6's. If we do that we have a working API again.
This is hard because parts of the code are not easily accessible. We need people that can decompile and document parts of the code!
Please keep the talking only about the API, no personal lives, let the programmers do their job.
Again were not looking for theories on how unknown6 is created, what values go in it. We will 99% sure only get a working API if we locate and understand the code creating unknown6.
If you think you can help, this document will bring you up to speed on the technical side of the issue. https://docs.google.com/document/d/1gVySwQySdwpT96GzFT9Tq0icDiLuyW1WcOcEjVfsUu4"

You can replace Discord with Github to match our discussion but please read it and stop asking why it is not working was published on reddit by DutchDefender

**Comment by Attacker-x** [comment] 2016-08-04 11:29
ggwp 😬.  continue your great works :). we await

**Comment by dodogtg** [comment] 2016-08-04 11:37
nice bro xAzzzu :smile:

**Comment by ade182** [comment] 2016-08-04 11:41
And so still many baby pig asking why is there are no pokestops ~

**Comment by mastercoyin** [comment] 2016-08-04 11:45
Lol pig :v

**Comment by jmo93** [comment] 2016-08-04 11:46
Donate to this great man!

**Comment by LvGPoke** [comment] 2016-08-04 11:47
imma big pig braaaah

**Comment by xAzzzu** [comment] 2016-08-04 11:48
@dodogtg Yeah but i think many people won't read it anyway maybe i should start a new thread

**Comment by Attacker-x** [comment] 2016-08-04 11:49
:) how to use mit proxy on windows?

**Comment by motemo77** [comment] 2016-08-04 11:51
pig? baby pig? we're calling names now?

**Comment by DokiTeeX** [comment] 2016-08-04 12:04
Now we can see how the life is difficult without this bot haha! :laughing:

**Comment by fnodnarb** [comment] 2016-08-04 12:08
Will this help at all? 
http://www.i4u.com/2016/08/114046/niantic-breaks-pokemon-go-apis-and-all-bots-and-trackers-based-apis  
Somebody in YouTube comments said @:15 -- so it looks like unknown6 does have a timestamp. Thanks!﻿

**Comment by Maybones** [comment] 2016-08-04 12:10
Can you give me a account ? Pls

**Comment by Sturmgrenadier** [comment] 2016-08-04 12:15
https://www.youtube.com/watch?v=WhryILX3NI0&feature=youtu.be

**Comment by stormlolz** [comment] 2016-08-04 12:17
@Maybones gift

https://club.pokemon.com/us/pokemon-trainer-club/sign-up/

**Comment by fnodnarb** [comment] 2016-08-04 12:43
http://pastebin.com/upXpS6D9

**Comment by HaydarOzturk** [comment] 2016-08-04 12:44
@Ar1i check the latest comments mybe they are useful! :)

**Comment by Nomad52** [comment] 2016-08-04 12:44
They cracked the Unknown 6, hopefully Ar1i will see this as soon as possible.

**Comment by yashmhatre** [comment] 2016-08-04 12:48
@Ar1i  check the recent comment it may help u out. :)

**Comment by UltraVLT** [comment] 2016-08-04 12:51
@everyone Unkown 6 was finally resolved. Thanks to all api debuggers! We now have to start work on implementing things into code and wait for a decryption.
@everyone Don't thank us, thank all API Reverser over at  /R/pokemongodev !

**Comment by HaydarOzturk** [comment] 2016-08-04 12:53
@whitemouse14 You can donate https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RUNUBQEANCAGQ trough this link buddy.

**Comment by ScarAce1989** [comment] 2016-08-04 13:01
Can't wait till this is fixed. Good luck guys! :)

**Comment by whitemouse14** [comment] 2016-08-04 13:13
@HaydarOzturk thanks mate, it seems i cant donate 
I already filled in the blank (in germany) and it appeared like this below 

Die Registrierung Ihrer Kreditkarte kann zurzeit nicht verarbeitet werden. Wir bedauern eventuelle Unannehmlichkeiten. Versuchen Sie es zu einem späteren Zeitpunkt erneu

Lol, 
Pls wait i will sign up for paypal first.
Sorry all 😌😌

**Comment by Deenaiy** [comment] 2016-08-04 13:18
Great work! Wollte nur mal kurz Danke sagen!@Ar1i danke, das du dir solche mühe für uns machst !

**Comment by pokerave** [comment] 2016-08-04 13:19
Map of PokeMesh got it reversed engineered
![map](https://cloud.githubusercontent.com/assets/20603254/17403175/4327ee28-5a5f-11e6-8683-9e4123f0a1bc.jpg)

**Comment by pokerave** [comment] 2016-08-04 13:26
READ This Please #1306

**Comment by adman9031** [comment] 2016-08-04 14:02
I guess I have to go back to playing the "old fashioned" way. And by that I mean using the poke go ++ tweak for jail broken iPhones lol.

**Comment by sseduppp718** [comment] 2016-08-04 16:40
i totally blind..no pokivsion no bot.....just walk around my house and i see just ratata...omg

**Comment by Daniel140** [comment] 2016-08-05 13:55
ITS CRACKED !!!! https://twitter.com/RedditPokeGoDev/status/761551903499182080  


#unknown6 problem has been cracked. src in node.js, python and java here https://www.sendspace.com/file/wtaqj0  @NianticLabs @PokeVisionGo

**Comment by bautschi44** [comment] 2016-08-05 20:56
Hi und wie sieht nun die Lage aus? Bin eh sicher der 1000te der frägt nur ich kann das Englisch nicht lesen😬

**Comment by lordminion** [comment] 2016-08-06 02:34
Also laut ar1 seiner Info geht der bor noch nicht er brauch noch etwas Zeit das neu zu knacken, ich habe das gleiche Problem komme nicht mal mit meinem normalen App zum Spielen bzw ich kann einloggen laufen Pokémon angucken schicken yeah aber ich sehe keine Arena keine pokestops keine Pokémon ;) ich denke wir sollten einfach etwas warten

**Comment by NidiKea** [comment] 2016-08-06 06:52
Ich hoffe auch, dass es sich überhaupt lösen lässt

**Comment by whitemouse14** [comment] 2016-08-06 09:45
for all of you who doesnt have a patience,
i have a method of mine which so far still working, 

this method only works well on my s7 edge, (no root, 6.01 )

* you need fly GPS *
* developer option, then choose it fly GPS/Fake Gps *
*open it, then choose location, then select it with pokemon joystick *
* open pokemon go and enjoy *

if you cant pokestop, then it means you're banned, so try to roll it pokestop by opening pokestop then dice, close it, then open and dice again, until it works. usually it takes 35 times,

soorry if some of you already knew this thing,
the problem is, i used to use this way with pokescaner now since all pokevision & pokescan &etc going down, i'm only able to use this with no direction, means that im not able to find out pokemon nearby, it sucks, it really is. but better than do nothing right

thanks :)

**Comment by FoolYah** [comment] 2016-08-06 10:20
Pokemon Joystick?

Am 06.08.2016 11:45 schrieb "whitemouse14" <notifications@github.com>:

**Comment by lordminion** [comment] 2016-08-06 15:45
Leider kann ich mit meinem normalen App auch nicht spielen, da liegt es wohl daran das ich im Pokémon Trainer Club registriert bin , bei alle die ich kenne mit Google Account geht es... Liegt wohl daran das das auf verschiedene Server liegt... Es nervt 😞😭

**Comment by itzjaydon** [comment] 2016-08-06 23:59
heard  the news great work guys

**Comment by Economy123** [comment] 2016-08-07 07:45
@Ar1i how far have u come last night? :D

**Comment by Attacker-x** [comment] 2016-08-07 12:39
necrobot already working

**Closed** 2016-08-07 13:25 UTC
Labels: READ BEFORE CREATE A NEW ISSUE

**Comment by lordminion** [comment] 2016-08-07 20:06
Sure? I try it and alwas got errors, First lt works now lot of red Text

**Comment by onnlinetool** [comment] 2017-04-10 11:00
Downloaden Knack  Downloaden Knack  Downloaden Knack

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw
