### ISSUE TITLE
Cant take any pokestops tried many different locations like times square santa monica central park and so on

### ISSUE THREAD

**Issue by tguuu** [Ar1i/PokemonGo-Bot#2980] opened 2016-08-11 19:56 UTC
![image](https://cloud.githubusercontent.com/assets/20977415/17602746/425c8d14-600e-11e6-9d60-96fc27c66bb0.png)

**Comment by PokePro21** [comment] 2016-08-11 19:58
same for me with another account

**Comment by schn33man** [comment] 2016-08-11 19:58
same

**Comment by waldiludi** [comment] 2016-08-11 20:00
they changed the api or sth. I can only see pokestops on moblie with mobile data. In wi-fi they aren't there. New try to fight bots i think. But @Ar1i will fix this soon i hope <3

**Comment by daredevil88** [comment] 2016-08-11 20:04
u guys ip banned try to restart your router or get a new ip and don't start more than one bot or don't start bot and map finder together or any program that use pokemon go

**Comment by DVD-DY** [comment] 2016-08-11 20:13
All say the answer is IP banned but i try 12 different IPs and still the same We can't find any PokeStops... any real solution??

**Comment by Heuk** [comment] 2016-08-11 20:15
same problem, new ip doesnt fix it, proxy doesnt fix it, new location doesnt fix it, running one bot only, it works fine in cellphone 
also its not an ip ban... there is no static ip in my country every reset gets a new public ip, i used diferent proxys non works, i dont know what it is but is not an ip ban....

**Comment by PCKGOHCKTEAM** [comment] 2016-08-11 20:19
Same here.

**Comment by Ar1i** [comment] 2016-08-11 20:20
Try to change your location?

**Comment by Ar1i** [comment] 2016-08-11 20:20
But be sure it isnt an IP ban. Proxys could be if they are public already used & banned.

**Comment by Ar1i** [comment] 2016-08-11 20:22
Could be servers too http://www.mmoserverstatus.com/pokemon_go

**Comment by Heuk** [comment] 2016-08-11 20:25
tried location change and it didnt work, my public ip changes everytime i restar my router because my isp doensyt offer a static ip services 

but there is onwe thing i have to mention, when this problem started happening to me i tried al older version of the bot and it worked like a charm, (i dont remeber the version ... :( ) no newer version worked :(

**Comment by PCKGOHCKTEAM** [comment] 2016-08-11 20:31
Restart Router - Fix it.

**Comment by DVD-DY** [comment] 2016-08-11 20:31
its true, if ip is banned why works the old version? for me works 1.0.7.6

I have 7 internet connections with 7 different routers and IPs. all say the same We can't find any PokeStops...  but works with old version.

**Comment by PCKGOHCKTEAM** [comment] 2016-08-11 20:33
Hey Ar1i, ich weiß du hast wahrscheinlich viel zu tun, aber kannst du erklären wie das mit den verschieden Ips funktioniert? das man Quasi mehrere Accounts gleichzeitig laufen lassen kann?

Danke im Voraus!
Mach weiter so!

**Comment by Ar1i** [comment] 2016-08-11 20:33
@DVD-DY that makes no sense.. your using a proxy orso? Cause in the Old Version the Proxy was buggy af.

**Comment by Ar1i** [comment] 2016-08-11 20:34
@PCKGOHCKTEAM musst nen HTTPS Private Proxy kaufen oder dir selbst einen machen wenn du nen Server besitzt und den unter Proxy eintragen

**Comment by Heuk** [comment] 2016-08-11 20:34
the old version i used didnt have the proxy option yet..

**Comment by PCKGOHCKTEAM** [comment] 2016-08-11 20:34
@Ar1i  danke dir!
Weiter so, danke für alles! :P

**Comment by Ar1i** [comment] 2016-08-11 20:34
@Heuk and it still works?

**Comment by DVD-DY** [comment] 2016-08-11 20:36
@Ar1i @Heuk Yes the 1.0.7.6 no have proxy option too and works perfect

**Comment by Ar1i** [comment] 2016-08-11 20:36
And if you use the new Version it wont work? You sure? If yes, i probably got an Idea.

**Comment by waropatrik1234** [comment] 2016-08-11 20:37
Same here

**Comment by DVD-DY** [comment] 2016-08-11 20:38
@Ar1i  yes the new version dont works but works the old version

**Comment by Heuk** [comment] 2016-08-11 20:39
iam pretty sure it was that version but i deleted it from my computer :( can i please get a link to try it?

**Comment by DVD-DY** [comment] 2016-08-11 20:40
i can upload the old version if you need it

**Comment by Heuk** [comment] 2016-08-11 20:40
please =)

**Comment by Ar1i** [comment] 2016-08-11 20:40
Hmm k, will push an update in some minutes if i am done, where i put a device.xml config.. which you can configure yourself. probably that fixes something

**Comment by DVD-DY** [comment] 2016-08-11 20:43
here is the link for old version https://www.mediafire.com/?ei1kz75tkg2kgb4

**Comment by DVD-DY** [comment] 2016-08-11 20:44
@Ar1i ok i wait for the update thank you very much

**Comment by Heuk** [comment] 2016-08-11 20:46
ty @DVD-DY and ty very much @Ar1i

**Comment by LeergutLars** [comment] 2016-08-11 20:50
@Ar1i yoAr1i - hab' mich momentan gar nicht informiert, Kumpel hat mich heute auf die Idee gebracht zu botten - funktioniert dein Bot mit dem neusten Update? Wie siehts aus mit IP-Bans? Irgendwelche Tipps um die Ban-chance zu minimieren?

thanks dude

**Comment by Heuk** [comment] 2016-08-11 20:53
i can confirm that 07.08 21.04 works perfrctly
![sin titulo](https://cloud.githubusercontent.com/assets/20891641/17604515/c356c638-5fdb-11e6-92c1-a03f057ad446.png)

**Comment by raineshh** [comment] 2016-08-11 21:04
same problem here

**Comment by RealChaosity** [comment] 2016-08-11 21:04
and here

**Comment by raineshh** [comment] 2016-08-11 21:05
I restarted my modem and not solved

**Comment by schn33man** [comment] 2016-08-11 21:09
Die alte Version funktioniert tadellos!  Danke Leute <3

**Comment by Ar1i** [comment] 2016-08-11 21:52
@Heuk @schn33man @DVD-DY could you try the newest version please?

**Comment by serge55555** [comment] 2016-08-11 22:07
Hello @Ar1i ,
I have same problem than the others, even with the new version.
I tried nexus5, galaxy6 and xperia z-5 as device, and I still can't find pokestops. I also changed my location.

Thank you for all your work <3

**Comment by DVD-DY** [comment] 2016-08-11 22:20
@Ar1i  i tried the newest with 3 IPs and say the same We can't find any PokeStops... I will try to change the device.txt for my device id and say you.

**Comment by Leyts5** [comment] 2016-08-11 22:20
@Ar1i I reverted to a previous version which works absolutely perfect. The only bad thing is no proxy but not super needed.

**Comment by Heuk** [comment] 2016-08-11 22:24
just finished trying for all the devices on 11.08 23.54 none of them worked  ill try with  12.08 00.16 now

**Comment by DVD-DY** [comment] 2016-08-11 22:30
i tried 12.08 00.16 with my personal device id and no work, maybe is a problem with the location or altitude.

**Comment by Ar1i** [comment] 2016-08-11 22:31
i dont know then, will close this..

**Closed by Ar1i** 2016-08-11 22:31 UTC

**Comment by DVD-DY** [comment] 2016-08-12 00:28
I found the problem!!!!

**Comment by DVD-DY** [comment] 2016-08-12 00:29
@Ar1i i know whats is the problem

**Comment by Heuk** [comment] 2016-08-12 00:32
whats the problem? :-O

**Comment by DVD-DY** [comment] 2016-08-12 00:35
the altitude, when you change the altitude detects pokestops

Please a fix update @Ar1i

**Comment by DVD-DY** [comment] 2016-08-12 00:36
for example my altitude is 2534 i change to 15 and works :D

**Comment by Heuk** [comment] 2016-08-12 00:51
omfg!!! haha gonna try right now =)

**Comment by Heuk** [comment] 2016-08-12 00:54
works!!!!

**Comment by DVD-DY** [comment] 2016-08-12 00:57
i say you the problem is the altitude

**Comment by Heuk** [comment] 2016-08-12 01:07
and you were right my friend thanks a lot

**Comment by DVD-DY** [comment] 2016-08-12 02:28
@Heuk I make a new issue with images of this problem, if you can comment here #3034 for a fix update
