### ISSUE TITLE
Transfer first lowest IV

### ISSUE THREAD

**Issue by Can7** [Ar1i/PokemonGo-Bot#2539] opened 2016-08-10 11:46 UTC
Can anyone explain this specification with an example ?

**Comment by PokeMungo** [comment] 2016-08-10 11:52
omfg. it is self explanatory! "Transfer first lowest IV "

**Comment by Can7** [comment] 2016-08-10 11:53
It can not work i think. Check or not it always transfer low IV.Even <90 IV

**Comment by Requal** [comment] 2016-08-10 11:57
Because your pokemon are higher than 90 maybe?
The option works as intended.

If you dont get it stop using the program...

**Comment by xRealMaks** [comment] 2016-08-10 11:58
If you got more than your max same pokemon amout of a pokemon, the bot would transfer the lowest CP pokemon. If you enable the function, the bot transfers the lowest IV one.

**Comment by Captnred** [comment] 2016-08-10 12:01
If you are posting a issue make sure it's an issue. You can post suggestions here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better-suggestions.51108/
Please close this thread as it is not an issue.

**Closed** 2016-08-10 12:02 UTC

**Comment by xRealMaks** [comment] 2016-08-10 12:04
@Captnred its a question, not a sugestion.
Please ask your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
