### ISSUE TITLE
Pokestop not giving items?

### ISSUE THREAD

**Issue by Theseppinator** [Ar1i/PokemonGo-Bot#3423] opened 2016-08-28 19:52 UTC
I have run some tests, I have disabled pokemon catching and just grinded central park for a certain period of time, I don't know the exact number, but **after about 5 min the bot doesn't show what he got from the stops anymore**, he will **recognize** them **and** (I guess?) **spin** them. Is this only a visual glitch or an acutal bug?

![glitch2](https://cloud.githubusercontent.com/assets/21261582/18036396/a2722cf0-6d69-11e6-9ecd-446c96a95024.png)

**Comment by Andy217ACE** [comment] 2016-08-28 20:16
Same here only XP

**Comment by PrOCheaTer** [comment] 2016-08-28 20:52
use your brain and fix it...

C&P:

` Logger.ColoredConsoleWrite(ConsoleColor.Cyan, "Pokemon(s): " + await _client.Inventory.getPokemonCount() + "/" + profile.PlayerData.MaxPokemonStorage + " Egg: " +await _client.Inventory.GetEggsCount() + " (" + pokemonToEvolve + " Evolved)");`

**Comment by jay-2-rome** [comment] 2016-08-29 05:37
Bist du dumm oder so?
Wie soll uns deine Antwort weterhelfen? 

Ich denke wenn du eine Frage stellt hättest du auch gerne eine Verständliche Antwort, Vollhorst!

**Comment by Kidnub** [comment] 2016-08-29 06:59
pls guys check your inventory Setups mostly it is the full inventory ... if you dont grab items... 
i can just say the bot works fine for me ... ;( ( even the old version works perfect for me before)
http://www2.pic-upload.de/img/31574942/Unbenannt.jpg
if you inventory is full you wont get items and think you have only 350 items on a basic account... XD
so check your inventory setup ... 
 my setup is like this for an example XD
http://www2.pic-upload.de/img/31574946/Unbenannt1.jpg
 and if you have put of the catch option think twice, you will have fast a full inventory ;( 
i hope the 2Screens will help you a bit ...


und @jay-2-rome das kannst du ihm auch netter sagen das sein commentar nicht der beste ist XD

**Comment by Aid-en** [comment] 2016-08-29 08:14
Im getting the same problem.... no one has answered me either: https://github.com/Ar1i/PokemonGo-Bot/issues/3402

**Comment by jay-2-rome** [comment] 2016-08-29 09:19
@Kidnub 
I'm having 208/350 items in my bag atm. I have my config set up to NEVER carry more then 280-330 items... But closing the bot and restarting a few times helped. Now looting stops again...

Ja und sorry für den Post vorhin aber im Ernst, was will der uns damit sagen? Ich geh doch nicht da im Quellcode rumpfuschen und fang mir schon wieder einen Ban ein. Ich verdiene Geld mit Accounts. Hab jetzt schon fast 20 gebannte. Man rechne sich aus was für ein Verlust das ist bei 20-50 pro Account...

**Comment by Kidnub** [comment] 2016-08-29 09:43
you miss you get level up items they are not counted XD

**Comment by Theseppinator** [comment] 2016-08-29 10:24
> pls guys check your inventory Setups mostly it is the full inventory ... if you dont grab items... 
i can just say the bot works fine for me ... ;( ( even the old version works perfect for me before)
http://www2.pic-upload.de/img/31574942/Unbenannt.jpg
if you inventory is full you wont get items and think you have only 350 items on a basic account... XD
so check your inventory setup ... 
my setup is like this for an example XD
http://www2.pic-upload.de/img/31574946/Unbenannt1.jpg
and if you have put of the catch option think twice, you will have fast a full inventory ;( 
i hope the 2Screens will help you a bit ...

I tried this, didn't work.

**Comment by PrOCheaTer** [comment] 2016-08-29 10:30
@jay-2-rome Na du kleiner 11 Jähriger Bengel... Macht es Spaß einen Helfenden direkt als Dumm zu bezeichnen?
Benutze dein Gehirn ( Ach sorry, schon bemerkt da ist keins vorhanden ) 
Da ist ein Fix du Bengel damit die Stats geupdated werden...

Erst Denken dann Antworten, vollhorst!

**Comment by MTK4355** [comment] 2016-08-29 10:35
Try a speed of 5-9 km/hr and select all pokemon in the "Pokeon not to catch" config for a quick test

There might be a bug here, but I have personally only seen this happen at high speeds.

At any rate, 100% of the accounts I have used at speeds over 15km/hr have been banned, even when limiting the total pokestops and pokemon per day..

**Comment by GiaPune** [comment] 2016-08-29 10:35
I have the same question...
https://i.imgur.com/l6srq8A.png

**Comment by Theseppinator** [comment] 2016-08-29 10:36
> At any rate, 100% of the accounts I have used at speeds over 15km/hr have been banned, even when limiting the total pokestops and pokemon per day.

I use 14KM/H

I'll try it right now tough.

**Comment by Aid-en** [comment] 2016-08-29 10:36
@PrOCheaTer how do I fix it then?

**Comment by PrOCheaTer** [comment] 2016-08-29 10:37
you have skype? i can give you a update...

**Comment by Aid-en** [comment] 2016-08-29 10:38
no sorry... i think its a bug... Ill just wait till its fixed or ill use hackermon (sad but necessary lmao)

**Comment by PrOCheaTer** [comment] 2016-08-29 10:40
ill fixed this prob. the code you see is the fix...

**Comment by PrOCheaTer** [comment] 2016-08-29 10:44
fixed.. 

![unbenannt](https://cloud.githubusercontent.com/assets/21296910/18049090/564ef09c-6de6-11e6-85cb-7111cdc6db26.png)

**Comment by Aid-en** [comment] 2016-08-29 10:53
how do i use the code: i hate being a drag but im not very cody hahaha

**Comment by Theseppinator** [comment] 2016-08-29 11:12
> Try a speed of 5-9 km/hr and select all pokemon in the "Pokeon not to catch" config for a quick test
There might be a bug here, but I have personally only seen this happen at high speeds.
At any rate, 100% of the accounts I have used at speeds over 15km/hr have been banned, even when limiting the total pokestops and pokemon per day..

Same thing

**Comment by PrOCheaTer** [comment] 2016-08-29 11:23
@Aid-en Download it and go: [http://ul.to/kguagump](url)

**Comment by Aid-en** [comment] 2016-08-29 11:28
@Theseppinator so is it fixed for you?

**Comment by Aid-en** [comment] 2016-08-29 11:29
@PrOCheaTer link doesnt work

**Comment by PrOCheaTer** [comment] 2016-08-29 11:44
hm. working fine for me

**Comment by Ar1i** [comment] 2016-08-29 11:48
No links allowed. @PrOCheaTer what do you added exactly? Or what do you changed?

**Comment by Aid-en** [comment] 2016-08-29 11:52
@Ar1i to the rescue! is this a issue on our side? are we doing something wrong? <3

**Comment by Monadologie** [comment] 2016-08-29 12:03
I'm getting the same issue.
Just for information there are my logs:

[13:43:40] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[13:43:43] -----------------------[PLAYER STATS]-----------------------
[13:43:43] Level/EXP: 21 | 58 415/75 000 (77,89%)
[13:43:43] EXP to Level up: 16585
[13:43:43] PokeStops visited: 2107
[13:43:43] KM Walked: 70,22
[13:43:44] Pokemon: 139 + 9 Eggs /250 (35 Evolvable)
[13:43:44] Pokedex Completion: 62/150 [41%]
[13:43:45] Items: 278/350
[13:43:45] Stardust: 95 242
[13:43:45] ------------------------------------------------------------
[13:43:45] Pokemon Catch Count this session: 0
[13:43:45] PokeStop Farmed Count this session: 0
[13:43:45] pokeBalls Qty: 26
[13:43:45] greatBalls Qty: 104
[13:43:45] ultraBalls Qty: 107
[13:43:45] ------------------------------------------------------------
[13:43:47] Egg (5km) need to walk 1,03 km.
[13:43:47] Egg (5km) need to walk 2,16 km.
[13:43:47] Egg (5km) need to walk 3,77 km.
[13:43:49] Transfer Paras CP 11 IV 51,99 % (Best: 438 CP)
[13:43:50] Transfer Magikarp CP 10 IV 48,22 % (Best: 137 CP)
[13:43:52] We found 240 usable PokeStops near your current location.
[13:43:52] Next Pokestop: Armures Sur La Corniche in 14,79m distance.
[13:43:52] Distance to target location: 14,79 meters. Will take 4,84 seconds!
[13:43:53] We are within 40 meters of the target. Slowing down to ~10 km/h to not pass the target.
[13:44:55] This bot is absolutely free and open-source!
[13:44:55] If you've paid for it. Request a chargeback immediately!
[13:44:55] Starting Execute on login server: Ptc
[13:44:55] Setting Pokemon Catch Count: to 0 for this session
[13:44:55] Setting Pokestop Farmed Count to 0 for this session
[13:44:59] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[13:45:02] -----------------------[PLAYER STATS]-----------------------
[13:45:02] Level/EXP: 21 | 58 415/75 000 (77,89%)
[13:45:02] EXP to Level up: 16585
[13:45:02] PokeStops visited: 2107
[13:45:02] KM Walked: 70,22
[13:45:03] Pokemon: 137 + 9 Eggs /250 (35 Evolvable)
[13:45:03] Pokedex Completion: 62/150 [41%]
[13:45:03] Items: 276/350
[13:45:03] Stardust: 95 242
[13:45:03] ------------------------------------------------------------
[13:45:03] Pokemon Catch Count this session: 0
[13:45:03] PokeStop Farmed Count this session: 0
[13:45:03] pokeBalls Qty: 26
[13:45:03] greatBalls Qty: 104
[13:45:03] ultraBalls Qty: 107
[13:45:03] ------------------------------------------------------------
[13:45:06] Egg (5km) need to walk 1,03 km.
[13:45:06] Egg (5km) need to walk 2,16 km.
[13:45:06] Egg (5km) need to walk 3,77 km.
[13:45:08] We found 240 usable PokeStops near your current location.
[13:45:09] Next Pokestop: Armures Sur La Corniche in 14,79m distance.
[13:45:09] Distance to target location: 14,79 meters. Will take 3,33 seconds!
[13:45:10] We are within 40 meters of the target. Slowing down to ~10 km/h to not pass the target.
[13:46:51] Found 1 catchable Pokemon(s).
[13:46:51] Encountered Rattata CP 160 IV 32,71% Probability 43%
[13:46:52] Caught Rattata CP 160 IV 32,71% using ItemPokeBall got 210 XP.
[13:46:54] Next Pokestop: Plaque Hommage Et Dévouement  in 52,33m distance.
[13:46:54] Distance to target location: 52,33 meters. Will take 26,91 seconds!
[13:48:40] This bot is absolutely free and open-source!
[13:48:40] If you've paid for it. Request a chargeback immediately!
[13:48:40] Starting Execute on login server: Ptc
[13:48:40] Setting Pokemon Catch Count: to 0 for this session
[13:48:40] Setting Pokestop Farmed Count to 0 for this session
[13:48:40] Altidude was 0, resolved that. New Altidude is now: 9,75339661140961
[13:48:44] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[13:48:48] -----------------------[PLAYER STATS]-----------------------
[13:48:48] Level/EXP: 21 | 58 625/75 000 (78,17%)
[13:48:48] EXP to Level up: 16375
[13:48:48] PokeStops visited: 2107
[13:48:48] KM Walked: 70,24
[13:48:48] Pokemon: 138 + 9 Eggs /250 (36 Evolvable)
[13:48:48] Pokedex Completion: 62/150 [41%]
[13:48:49] Items: 277/350
[13:48:49] Stardust: 95 342
[13:48:49] ------------------------------------------------------------
[13:48:49] Pokemon Catch Count this session: 0
[13:48:49] PokeStop Farmed Count this session: 0
[13:48:49] pokeBalls Qty: 25
[13:48:49] greatBalls Qty: 104
[13:48:49] ultraBalls Qty: 107
[13:48:49] ------------------------------------------------------------
[13:48:51] Egg (5km) need to walk 1,01 km.
[13:48:51] Egg (5km) need to walk 2,14 km.
[13:48:51] Egg (5km) need to walk 3,75 km.
[13:48:54] We found 239 usable PokeStops near your current location.
[13:48:54] Next Pokestop: Place Dauphine in 21,88m distance.
[13:48:54] Distance to target location: 21,88 meters. Will take 7,88 seconds!
[13:49:44] Pausing at next Pokestop. (will continue catching pokemon and farming pokestop when available)
[13:49:47] Resume walking between Pokestops.
[13:52:59] This bot is absolutely free and open-source!
[13:52:59] If you've paid for it. Request a chargeback immediately!
[13:52:59] Starting Execute on login server: Ptc
[13:52:59] Setting Pokemon Catch Count: to 0 for this session
[13:52:59] Setting Pokestop Farmed Count to 0 for this session
[13:52:59] Altidude was 0, resolved that. New Altidude is now: 9,70605528670018
[13:53:05] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[13:53:08] -----------------------[PLAYER STATS]-----------------------
[13:53:08] Level/EXP: 21 | 58 625/75 000 (78,17%)
[13:53:08] EXP to Level up: 16375
[13:53:08] PokeStops visited: 2107
[13:53:08] KM Walked: 70,24
[13:53:08] Pokemon: 138 + 9 Eggs /250 (36 Evolvable)
[13:53:08] Pokedex Completion: 62/150 [41%]
[13:53:09] Items: 277/350
[13:53:09] Stardust: 95 342
[13:53:09] ------------------------------------------------------------
[13:53:09] Pokemon Catch Count this session: 0
[13:53:09] PokeStop Farmed Count this session: 0
[13:53:09] pokeBalls Qty: 25
[13:53:09] greatBalls Qty: 104
[13:53:09] ultraBalls Qty: 107
[13:53:09] ------------------------------------------------------------
[13:53:12] Egg (5km) need to walk 1,01 km.
[13:53:12] Egg (5km) need to walk 2,14 km.
[13:53:12] Egg (5km) need to walk 3,75 km.
[13:53:15] We found 240 usable PokeStops near your current location.
[13:53:15] Next Pokestop: Armures Sur La Corniche in 25,58m distance.
[13:53:15] Distance to target location: 25,58 meters. Will take 9,21 seconds!
[13:54:34] This bot is absolutely free and open-source!
[13:54:34] If you've paid for it. Request a chargeback immediately!
[13:54:34] Starting Execute on login server: Ptc
[13:54:34] Setting Pokemon Catch Count: to 0 for this session
[13:54:34] Setting Pokestop Farmed Count to 0 for this session
[13:54:38] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[13:54:41] -----------------------[PLAYER STATS]-----------------------
[13:54:41] Level/EXP: 21 | 58 625/75 000 (78,17%)
[13:54:41] EXP to Level up: 16375
[13:54:41] PokeStops visited: 2107
[13:54:41] KM Walked: 70,24
[13:54:42] Pokemon: 138 + 9 Eggs /250 (36 Evolvable)
[13:54:42] Pokedex Completion: 62/150 [41%]
[13:54:42] Items: 277/350
[13:54:42] Stardust: 95 342
[13:54:42] ------------------------------------------------------------
[13:54:42] Pokemon Catch Count this session: 0
[13:54:42] PokeStop Farmed Count this session: 0
[13:54:42] pokeBalls Qty: 25
[13:54:42] greatBalls Qty: 104
[13:54:42] ultraBalls Qty: 107
[13:54:42] ------------------------------------------------------------
[13:54:45] Egg (5km) need to walk 1,01 km.
[13:54:45] Egg (5km) need to walk 2,14 km.
[13:54:45] Egg (5km) need to walk 3,75 km.
[13:54:47] We found 139 usable PokeStops near your current location.
[13:54:48] Next Pokestop: Général Gustave Ferrié in 10,55m distance.
[13:54:48] Distance to target location: 10,55 meters. Will take 9,5 seconds!
[13:56:02] Found 1 catchable Pokemon(s).
[13:56:03] Encountered Staryu CP 271 IV 67,38% Probability 45%
[13:56:04] Missed Staryu while using ItemPokeBall
[13:56:05] Caught Staryu CP 271 IV 67,38% using ItemPokeBall got 210 XP.
[13:56:06] Next Pokestop: Sculpture Cup in the Park in 85,11m distance.
[13:56:06] Distance to target location: 85,11 meters. Will take 43,77 seconds!
[13:57:48] This bot is absolutely free and open-source!
[13:57:48] If you've paid for it. Request a chargeback immediately!
[13:57:48] Starting Execute on login server: Ptc
[13:57:48] Setting Pokemon Catch Count: to 0 for this session
[13:57:48] Setting Pokestop Farmed Count to 0 for this session
[13:57:51] Export Player Infos and all Pokemon to "\Config\PokemonList.csv"
[13:57:55] -----------------------[PLAYER STATS]-----------------------
[13:57:55] Level/EXP: 21 | 58 835/75 000 (78,45%)
[13:57:55] EXP to Level up: 16165
[13:57:55] PokeStops visited: 2107
[13:57:55] KM Walked: 70,24
[13:57:55] Pokemon: 139 + 9 Eggs /250 (36 Evolvable)
[13:57:55] Pokedex Completion: 62/150 [41%]
[13:57:56] Items: 278/350
[13:57:56] Stardust: 95 442
[13:57:56] ------------------------------------------------------------
[13:57:56] Pokemon Catch Count this session: 0
[13:57:56] PokeStop Farmed Count this session: 0
[13:57:56] pokeBalls Qty: 23
[13:57:56] greatBalls Qty: 104
[13:57:56] ultraBalls Qty: 107
[13:57:56] ------------------------------------------------------------
[13:57:59] Egg (5km) need to walk 1,01 km.
[13:57:59] Egg (5km) need to walk 2,14 km.
[13:57:59] Egg (5km) need to walk 3,75 km.
[13:58:00] Transfer Staryu CP 168 IV 16,09 % (Best: 510 CP)
[13:58:02] We found 139 usable PokeStops near your current location.
[13:58:03] Next Pokestop: Général Gustave Ferrié in 10,55m distance.
[13:58:03] Distance to target location: 10,55 meters. Will take 3,8 seconds!
[13:59:33] Next Pokestop: Sculpture Cup in the Park in 84,09m distance.
[13:59:33] Distance to target location: 84,09 meters. Will take 27,52 seconds!
[13:59:46] Found 1 catchable Pokemon(s).
[13:59:47] Encountered Staryu CP 261 IV 52,88% Probability 45%
[13:59:48] Caught Staryu CP 261 IV 52,88% using ItemPokeBall got 210 XP.
[13:59:50] We are within 40 meters of the target. Slowing down to ~10 km/h to not pass the target.
[14:01:17] Next Pokestop: PANNEAU ÉTONNANT in 69,5m distance.
[14:01:17] Distance to target location: 69,5 meters. Will take 35,74 seconds!

**Comment by 133791** [comment] 2016-08-29 12:57
Same here ,
Lower catch rates =more wasted balls, then no new items from pokestops. its useless atm no exp :/

**Comment by 133791** [comment] 2016-08-29 12:59
Same here ,
Lower catch rates =more wasted balls, then no new items from pokestops, and no balls at all. its kinda useless atm no exp :/
![xcxc](https://cloud.githubusercontent.com/assets/21310670/18052194/2e3811ca-6df9-11e6-9fa7-bbf4681b5216.png)

**Comment by Theseppinator** [comment] 2016-08-29 13:55
Restarted the pokemon bot **3x** on **my IP**, **didn't work**. 
**Changed IP**
Restarted the pokemon bot **3x** on **another IP**, **didn't work**.
I can **acces my account on 2 different devices**.

Conclusion: **I'm not IP banned, I'm not perm banned**.
What is it then? O.o

![again](https://cloud.githubusercontent.com/assets/21261582/18053641/c6e012a4-6e00-11e6-8f8b-95d7aaeee965.png)

**Comment by jay-2-rome** [comment] 2016-08-29 15:37
Yea but walking around with max 10kmh doesn't make me level up my friend.
I'm stuck on level 22 for 3 days now... So you're wright but in my case you aren't ;-)

**Comment by MTK4355** [comment] 2016-08-29 17:03
I finally reproduced the issue and the response we are getting from the API is "Inventory full" even though my inventory is not actually full. Looks like it may be Niantic's bug or a new ban type. Standby while I investigate further.

**Comment by jay-2-rome** [comment] 2016-08-29 19:36
So should we modify our config to carry less stuff or what you think?

I just changed to 100x every type of ball + 50 berries. I don't need revives or potions until I'm high level and got high IV Pokemon... Or maybe set it to 75x balls + less berries? 

Every change on the config is a possible ban. I'm quite paranoid since Niantic started banning for no reason xD

**Comment by MTK4355** [comment] 2016-08-29 21:20
So on further investigation the items count was totally wrong... I think @Ar1i just merged in my new inventory logger that will give you the actual number of items in your inventory.  :)
![image](https://cloud.githubusercontent.com/assets/11677019/18067864/6c396824-6e04-11e6-9030-344a36364232.png)
Since bringing my inventory levels back down I haven't seen the issue resurface, but I'm withholding judgement on whether the problem is actually fixed until I hear from you guys....

**Comment by PrOCheaTer** [comment] 2016-08-30 11:52
@jay-2-rome Ei Ei, du kleiner Ghetto-Slanger..
Du hast ja ziemlich große Eier vor deinem Bildschirm.
Jetzt zeigst du mir noch größere indem du kleiner Spaten mir deine Adresse sagst.
Sreen-Großmäulern wie dir muss man nämlich mal die Ohren lang ziehen! 
Es scheint keinen Respekt in deiner "Familie" zu geben.
Da ich aber jetzt schon weiß dass du keine "Eier" hast mir deine Adresse zu geben, Rate ich dir jetzt noch mal ausdrücklich deine vorgehensweise im "Internet" ( eventuell auch in deinem Real-Live ) zu überdenken.

**Comment by jay-2-rome** [comment] 2016-08-30 19:46
Komm lass gut sein. Ich will dir nicht weh tun. Ich wohne übrigens in Koblenz/Lützel, Nähe Bahnhof. Wenn du willst komm mal vorbei dann gehen wir ne Shisha rauchen und trinken gemütlich einen Tee. Dann kannst du mir das noch mal ins Gesicht sagen wenn paar von meinen türkischen Habibis dabei sind xD

Wir haben uns auf dem falschen Fuß erwischt aber du solltest nicht so großkotzig sein mit deinem "use your brain", sowas kann ich gar nicht leiden. Der Kerl hat normal eine Frage gestellt und eine doofe Antwort bekommen, sehr uncool ...

**Comment by Logxn** [comment] 2016-09-06 07:32
@jay-2-rome 

"Ich wohne übrigens in Koblenz/Lützel, Nähe Bahnhof. Wenn du willst komm mal vorbei dann gehen wir ne Shisha rauchen und trinken gemütlich einen Tee. Dann kannst du mir das noch mal ins Gesicht sagen wenn paar von meinen türkischen Habibis dabei sind xD"

Pussy move. Haste angst allein zu kommen?

"Wir haben uns auf dem falschen Fuß erwischt aber du solltest nicht so großkotzig sein mit deinem "use your brain", sowas kann ich gar nicht leiden"

kein Grund zum hurensohn zu werden.
Inspector Logxn: Case Closed

**Closed by Logxn** 2016-09-06 07:32 UTC
