### ISSUE TITLE
No Pokestops in Range of 5000m with Windows server

### ISSUE THREAD

**Issue by Raiderman1105** [Ar1i/PokemonGo-Bot#1966] opened 2016-08-08 09:17 UTC
on My Windows Server i have the No Pokestops Problem but on my Home PC it works :/
same Version Same Configuration

**Comment by Thijscream** [comment] 2016-08-08 09:21
i would say it;s in your windows configuration. can't find any system requirements. maby it's the IE enhanced secuity configuration setting that needs to be disabled or firewall ports needs to be open. maby check the logs(event viewer).

**Comment by Raiderman1105** [comment] 2016-08-08 09:24
you mean maybe the port which connect with the PoGo API its closed ?

**Comment by Thijscream** [comment] 2016-08-08 09:28
try disabling the firewall completly for a minute. if the problem is resolved by then you can reenable it and start trying what ports to set to open.

**Comment by Raiderman1105** [comment] 2016-08-08 09:30
Firewall down.. it works but i really dont know which ports i have to open i just buy that Server for bots im not a port opener for me just excist Firewall on or off xD someone can help?

**Comment by Thijscream** [comment] 2016-08-08 09:34
you will have to contact the developers what ports needs to be open. else you have to check what ports are used with wireshark or something. not something i can do atm since i'm at my work pc.

**Comment by Raiderman1105** [comment] 2016-08-08 09:35
hm is there no Configuration :/?

**Comment by Thijscream** [comment] 2016-08-08 09:39
not that i'm aware of.

**Comment by Raiderman1105** [comment] 2016-08-08 09:44
http://prntscr.com/c307ao Maybe this could help?

**Comment by Ar1i** [comment] 2016-08-08 16:33
Switch location!

**Closed by Ar1i** 2016-08-08 16:33 UTC
