### ISSUE TITLE
multiple "Detected softban etc..." on two different accounts at the same time 

### ISSUE THREAD

**Issue by DrakeandJosh** [Ar1i/PokemonGo-Bot#714] opened 2016-08-01 08:55 UTC
don't have a snippet. Was too scary, so i closed out of it. It wasn't the normal softban by fast travelling. the "detected softban" started repeating itself. i was worried i was banned. I can still log into the app fine, but haven't tried farming pokestops or catching pokemon (i'll probs be softbanned for a while for travelling).  

not botting again until someone confirms this is just a prank.

**Comment by Caddyrn** [comment] 2016-08-01 09:02
Me too. I have Login 6 Accounts. All Accounts AT the Same time get softban.  He unbanned him self with Unban Script and Farming again

**Comment by stormlolz** [comment] 2016-08-01 09:10
Same with 3 accounts in same time

1 softban but the script deban me

**Comment by UltraVLT** [comment] 2016-08-01 09:11
could be because you farm in places where many are botting e.g central park.These accounts are pretty high risk atm and often get the softban message.All 3 of mine are getting these message often too,but the one in germany never had one,not even false positive.

**Comment by Logxn** [comment] 2016-08-01 09:16
just let it run, the bot will unban you lol

**Comment by Bikkstar123HD** [comment] 2016-08-01 09:28
same here soft ban multiple times and its constantly going softban soft ban soft ban damnnn thats risky i am a resident near central park lol i am not travelling there through teleport lol not sure whats the point

**Comment by Logxn** [comment] 2016-08-01 09:33
ffs.
They will ban you if you use central park as default location.
Go somewhere else. Las Vegas baby

**Comment by elenex23** [comment] 2016-08-01 09:34
Was able to see the first soft ban on two different computers, ptc and Google. Didn't even wait to get unban, just quit. Post above me says ban repeats itself.

**Comment by elenex23** [comment] 2016-08-01 09:35
I was at pier 1 San Francisco and downtown Disney california.

**Comment by Bikkstar123HD** [comment] 2016-08-01 09:37
bro i got unbanned twice today and i stay near central park i m not transporting to it lol i have been using this from last 4 days but got banned first time and unban method wasnt helping the cause

**Comment by elenex23** [comment] 2016-08-01 09:37
L

**Comment by Bikkstar123HD** [comment] 2016-08-01 09:38
@Logxn  can u tell me how to change location because its stuck to central park as default

**Comment by lailaps** [comment] 2016-08-01 09:40
Today new Pokemon GO update?
Hope the bot will still work!

**Comment by roberrrt-s** [comment] 2016-08-01 09:42
I've been softbanned when roaming Amsterdam Central station, as well as near my house.

**Comment by DrakeandJosh** [comment] 2016-08-01 09:42
![image](https://cloud.githubusercontent.com/assets/20755132/17290086/0db5689c-5820-11e6-98ec-a341363ef7ce.png)
this is constantly happening atm

**Comment by lailaps** [comment] 2016-08-01 09:44
No Softban here.

**Comment by stormlolz** [comment] 2016-08-01 09:45
SoftBan in France, Lyon
Not a place very populated

**Comment by Logxn** [comment] 2016-08-01 09:47
whats ur running speed?

**Comment by stormlolz** [comment] 2016-08-01 09:48
45km/h
4500meters radius

**Comment by Bikkstar123HD** [comment] 2016-08-01 09:51
25 and 3000 mts

**Comment by lailaps** [comment] 2016-08-01 10:08
I am always in Sydney.

**Comment by elenex23** [comment] 2016-08-01 10:15
lailaps could you tell us your run speed and meter radius?

**Comment by xhalfbakedguy** [comment] 2016-08-01 10:27
cant they just add a check for your ip and compare its location to where you are in Pokemon GO? i feel like its the easiest way to detect location spoofing..

**Comment by elenex23** [comment] 2016-08-01 11:15
I've slowed my walking speed to 10 and I have received no bans. I have one trainer at my local college and one at a popular zone, doesn't seem to affect it. I also turned my walking radius down to 1000 meters but I believe the issue is the walking speed.

**Comment by durnevo** [comment] 2016-08-01 11:42
I use 50km and 1000 meter radius, no problems for 3 days~

**Comment by lailaps** [comment] 2016-08-01 12:01
**@xhalfbakedguy**
Yes, I think that would be possible.
They don't need to track GPS data.
So german IP (no mobile IP) collecting stuff in Sydney ==> ban
Maybe in future!

**Comment by jansnxnxnsi** [comment] 2016-08-01 12:56
@lailaps Hey an welcher Stelle hast du die gefunden?:D

**Comment by Ar1i** [comment] 2016-08-01 14:32
change your location and it should be fixed

**Closed by Ar1i** 2016-08-01 14:32 UTC
