### ISSUE TITLE
Problem Use LuckyEgg if not running

### ISSUE THREAD

**Issue by rickepk** [Ar1i/PokemonGo-Bot#2611] opened 2016-08-10 15:26 UTC
All time to open app this option "Use LuckyEgg if not running" is true.
Dont save the config?
![image](https://cloud.githubusercontent.com/assets/20685209/17559717/97b09edc-5ef5-11e6-8638-226f6b00526a.png)

**Comment by BeeeMadre** [comment] 2016-08-10 15:29
This bot used all my lucky eggs... SAD :(

**Comment by Ar1i** [comment] 2016-08-10 15:51
Config system is kinda broken, recoding one this evening

**Comment by blahblah1227** [comment] 2016-08-10 15:59
untick the auto egg incubation to not use lucky egg. i believe thats where the problem is. but i dont want to waste another egg by logging in. after the timer ran out it didnt use another one before i logged out and checked in the game itself

**Comment by xRealMaks** [comment] 2016-08-10 17:24
Fixed in the newest version

**Closed by xRealMaks** 2016-08-10 17:24 UTC
