### ISSUE TITLE
Error while Loading list

### ISSUE THREAD

**Issue by programmar297** [Ar1i/PokemonGo-Bot#3051] opened 2016-08-12 04:25 UTC
Hi Ar1i,

I am getting this error when I start the bot. It doesn't go beyond this. And the Pokemon list is not loaded

![error](https://cloud.githubusercontent.com/assets/7389820/17612728/45cc1faa-6090-11e6-807c-891ff594e6b4.jpg)

**Comment by devilexclonz22** [comment] 2016-08-12 04:27
same on me ...

**Comment by timewizard19** [comment] 2016-08-12 04:29
use ur phone, maybe u got failed to login too #3044

**Comment by daniele978** [comment] 2016-08-12 04:29
eliminates the bots, and download a new copy
The problem is in the file Profile_yourusername_PokemonList.csv you there?

**Comment by bkrandy** [comment] 2016-08-12 04:30
@daniele978 but cant login using the phone app as well

**Comment by TwoMew** [comment] 2016-08-12 04:31
Same here. Its probably this #3044

**Comment by timewizard19** [comment] 2016-08-12 04:31
yup maybe its got servers side issue too

**Comment by crazyandy3** [comment] 2016-08-12 04:33
http://prntscr.com/c4oyy7   same here defuk my bot wos worcking fine then i close it to change account and this hapend

**Comment by TwoMew** [comment] 2016-08-12 04:35
I think we have to wait a few hours and hope its a server issue.

**Comment by daniele978** [comment] 2016-08-12 04:37
already tried with another account and proxy?

**Comment by crazyandy3** [comment] 2016-08-12 04:37
i think they change api agen -.-

**Comment by TwoMew** [comment] 2016-08-12 04:38
Now they didn't. Other accounts work on me..

**Comment by crazyandy3** [comment] 2016-08-12 04:42
NVM SERVERS down

**Comment by daniele978** [comment] 2016-08-12 04:43
It works for me

**Comment by crazyandy3** [comment] 2016-08-12 04:56
http://prntscr.com/c4p4hx   defuk  i cant log in game ... with other account i log in fine with the one i use boting i cant

**Comment by crazyandy3** [comment] 2016-08-12 05:14
guys its not bot problem..... its new  ban system  unlucky guys   some bot accounts got ban :/

**Comment by crazyandy3** [comment] 2016-08-12 05:18
"It appears  that there is a new type of ban happening. It does not appear to be an IP-ban, rather an account one. There is not many details yet, it is all a mix of speculations and rumors, but there is definitely something happening.

**Comment by Khorajuste** [comment] 2016-08-12 06:00
Pokemon go get an upgrade tonight 1.3.1

**Comment by crazyandy3** [comment] 2016-08-12 06:03
has nothing to do with the bans we got

**Comment by tmkhanh** [comment] 2016-08-12 06:19
Same problem with my account while others still run, not sure why.

The bot have been running around 15km/h and not receiving any soft ban for 2 days so far.

**Comment by Khorajuste** [comment] 2016-08-12 06:34
Upgrade 1.3.1 is only for iOS , I can't connect with my bot account AND my Vanilla account so I don't think it's a ban wave just A server problem :/ iOS Pokemon go don't work actually

**Comment by Khorajuste** [comment] 2016-08-12 06:34
Or too many connection

**Comment by Ar1i** [comment] 2016-08-12 09:25
#3074

**Closed by Ar1i** 2016-08-12 09:25 UTC
