### ISSUE TITLE
Succesfully evolved 0/0 Pokemons.

### ISSUE THREAD

**Issue by zzzz9999** [Ar1i/PokemonGo-Bot#2427] opened 2016-08-09 23:37 UTC
When click on Evolve button on Pokemon List dialog without selecting any Pokemon, bot says it evolved 0/0 Pokemon.  (maybe also with other buttons)
Not a critical bug, more like an enhancement :)

![bot1](https://cloud.githubusercontent.com/assets/20780971/17537200/81dbe2c8-5e92-11e6-81f9-385bdb24453e.png)

**Comment by DomeSs97** [comment] 2016-08-09 23:41
you must click on pokemon (facepalm)

**Comment by xRealMaks** [comment] 2016-08-09 23:42
^

**Comment by zzzz9999** [comment] 2016-08-09 23:44
Yeah I know, but still a bug!
If no Pokemon selected, button should do nothing at all!

**Comment by DomeSs97** [comment] 2016-08-09 23:52
just button must do anything? or what you mean Lol!

**Comment by zzzz9999** [comment] 2016-08-10 00:23
Button must do anything (or must not do a thing)
Well ...

**Comment by Captnred** [comment] 2016-08-10 01:27
This is not a bug, It's literally stating that 0 out of 0 pokemon have been evolved. In simple terms you asked it a question and it gave you an answer. Please close this thread.

**Comment by gummyruler** [comment] 2016-08-10 08:22
As what Siri said, “Imagine that you have zero cookies and you split them evenly among zero friends. How many cookies does each person get? See? It doesn’t make sense. And Cookie Monster is sad that there are no cookies, and you are sad that you have no friends.” If you click nothing the bot still tries to act, but in the end the result is nothing.

**Closed** 2016-08-11 11:17 UTC
Labels: minor bug
